### ISSUE TITLE
Time zone setting

### ISSUE THREAD

**Issue by Chris869218** [ehendrix23/tesla_dashcam#1]
A potentially useful setting would be the ability to change from UTC to the user’s preferred time zone on the displayed timestamp. Great tool, thanks for putting this out there!

**Comment by ehendrix23** [comment]
Do you mean the date/time within the merged video? This is ffmpeg itself doing it and in there I specify the parameters to put the date/time converted to user's timezone (based on timezone of PC).

I know that works on mine. :-) What version of ffmpeg do you run? What platform are you on?

**Comment by Chris869218** [comment]
Ah, awesome. I should have tried it out first, haven’t been home yet since I stumbled upon this. I was just used to looking at the video titles in UTC and it was the first thing that came to mind. Looking forward to playing around with it and having the local timestamp displayed. Close this unnecessary issue out, and thanks again!

**Comment by ehendrix23** [comment]
LMAO, no worries. Will do. :-)
