### ISSUE TITLE
Anyway to automate this?

### ISSUE THREAD

**Issue by bdeavilla** [ehendrix23/tesla_dashcam#110]
I have a raspberry pi that automatically uploads files to drive in my main computer.  I want to monitor that for new dashcam footage and then make the combined photos and delete the source footage.  Anyway to automate this?

**Comment by magicalyak** [comment]
@bdeavilla you can script it, I have the files upload to a server and run a cron job that move combined to another folder.  I delete the originals after 3 months unless there is an .archive file in there (which then skips).  Note I'm using globbing and bash in the .sh script.  Feel free to copy/modify if it's helpful.  I forked the repo and added an examples folder in my case.
https://github.com/magicalyak/tesla_dashcam/blob/dev/examples/teslausbarchive.sh

**Comment by raushel** [comment]
@bdeavilla I did this in PowerShell (with some other wrapping enhancements):

https://github.com/raushel/tesla_wrappers

**Comment by DaveRuijter** [comment]
I have used an Azure environment with Azure Batch to automate this. Blog posts can be found here: https://www.moderndata.ai/2020/01/automatic-teslacam-and-sentry-mode-video-processing-in-azure-part-1/

**Comment by hitnrun30** [comment]
@raushel love your scripts, but I'm a bit confused, I already have the teslausb setup to put the files on my NAS, I just want to combine it with my options (preferences file) and put the combined file in a folder.  I don't need all the fancy logging your doing.  Is there anyway you can update your Wiki with instructions to edit your PS files, also may i suggest creating a preferences file, that way it can be more dynamic

**Comment by raushel** [comment]
All of the logging is controlled in CMTraceLogger.ps1, but the variables used (including disable pushover are in VarLibrary.ps1 (this is essentially the preference file).

I can add an option to disable all file logging and add IFTTT pretty easily (both just require modifying CMTraceLogger.ps1, just need a bit to test.

**Comment by hitnrun30** [comment]
@raushel thank you so much I'll take a look, the only question is since I have the teslausb what do I do since copying of files is because of that?

**Comment by raushel** [comment]
Err, I wrote the wrappers early on before a preference file was an option, would have to take a closer look at that. Ultimately, ended up writing PowerShell logic to handle things that might be native now (Ie temp_dir, skip_existing, monitor_trigger).

With teslausb, just need to configure varlibary.ps1 with the path of your savedClips/sentryclips on your sync share. Add the extra parameters to line 73 in stitch teslacam for tesla_dashcam until I can look at adding support for preference file.

**Comment by hitnrun30** [comment]
@raushel I think I understand you now, I just need the stitchteslacam CMTracelogger and Varlibrary, change the Var library (I will add my preferences file and change line 73 (actually74)) The only point I need help with is the top of the stitch file.  First is the pip installs, are they needed, because I keep my system up to date and my installs are elsewhere.?  Second, does this make a file for all the files in a folder or one per grouping, I prefer one per grouping.

**Comment by raushel** [comment]
1) pip update is optional, the tesla_dashcam update is forced to a specific version in case an update breaks the rest of the script (I update this after validating new version).
2) This makes 1 file per grouping ie SentryClips\<datetime> will make 1 <datetime>.mp4, but if you have 4 event folders, you'll have 4 output mp4's

**Comment by hitnrun30** [comment]
ok, let me test, and I will add to your project, if you don't mind.  The only weird point I found is why you have an output folder but don't use it.  I put in the temp directory in my preferences and changed your code for output folder to be a specified instead of the folder it was created in.

**Comment by raushel** [comment]
Err, I see what you mean. Looks like I didn't update the varlibrary sample for that after making some changes. Should be: $Global:outputFolder = '\\teslausbshare\Stitched' (used to just point at the teslausb root and output into the specified subfolder).

**Comment by hitnrun30** [comment]
I'm almost there, but I'm still having the same issue I had before where it isn't resolving the source folder, I just keep getting "unrecognized arguments"

my command line is 
tesla_dashcam.exe @preferences.txt --output \\backup\TeslaCam\SentryClips\2020-02-03_18-28-16\2020-02-03_18-28-16.mp4 \\backup\TeslaCam\SentryClips\2020-02-03_18-28-16

**Comment by ehendrix23** [comment]
If I recall correctly, on Windows it would have to be like this:

tesla_dashcam.exe "@preferences.txt" --output \\backup\TeslaCam\SentryClips\2020-02-03_18-28-16\2020-02-03_18-28-16.mp4 \\backup\TeslaCam\SentryClips\2020-02-03_18-28-16

Notice the @preferences.txt in double quotes.

**Comment by hitnrun30** [comment]
Actually found the stupid reason, you have to put the preferences after the output, when I did that it worked.  Im going to test some more and update your Git if you want.

**Comment by ehendrix23** [comment]
I believe you can put it before output as well but it has to be in between quotes.

For the 2 files, will be fixed in next release.

**Comment by hitnrun30** [comment]
I tried it before the output and thats what led me here.

2 files would be great fix, it will take less time to process, when is the next release scheduled?

**Comment by hitnrun30** [comment]
I still have an issue with and it not merging all for the same day, I would think that is the easy part to do.

**Comment by hitnrun30** [comment]
@ehendrix23 can you assist me, I created a new ticket, but have had no answer.  it creates everything as wanted, but when it goes to combine the files for the day I am getting an error.

**Comment by ehendrix23** [comment]
Merging all together for 1 day will now easily be done in v0.1.117. Beta version just released: https://github.com/ehendrix23/tesla_dashcam/releases/tag/v0.1.17b1

**Comment by ehendrix23** [comment]
v0.1.18 has been released
