### ISSUE TITLE
Feature Request - 4k output

### ISSUE THREAD

**Issue by ChaDude** [ehendrix23/tesla_dashcam#112]
Any way to encode the output video in higher resolution? 4k would keep most of the original density in case details need to be pulled later - like a license plate in the distance etc.

**Comment by daverhunter** [comment]
Use the --scale 1280x960 flag in your config file.
This keeps each individual video at its original size which gives you a 3840x1920 output video (based on also using the --WIDESCREEN flag)

**Comment by ehendrix23** [comment]
Have you tried using parameter --quality? For file size there is also --compression

**Comment by ehendrix23** [comment]
Closing
