### ISSUE TITLE
View all 4 cameras as normal

### ISSUE THREAD

**Issue by 07stuntar1** [ehendrix23/tesla_dashcam#114]
Is there a way to combine all 4 cameras as non mirrored? Also is the quality of the video altered? When submitted footage it cannot be altered. ex. Mirrored. The only --mirror works without the front camera.
+---------------+----------------+----------------+
|               |  Front Camera  |                |
+---------------+                +----------------+
|   Right Camera |----------------| Left Camera   |
+               +  Rear Camera   +                +
|---------------|                |----------------|
+---------------+----------------+----------------+

**Comment by ehendrix23** [comment]
Use --rear option for this.

Quality overall is not altered but in the end it is re-encoding. Y can define quality using --quality and thus setting it higher then default for the re-encoding.
Further, using --scale you can also set the size for each camera (different sizes or all same size). Providing the value of 1 leaves the camera size to 1280x960.
