### ISSUE TITLE
Can't seem to get it to see/process a network share on Mac

### ISSUE THREAD

**Issue by steveclv** [ehendrix23/tesla_dashcam#117]
My Teslausb pi dumps all the footage onto 192.168.1.240 network share and I want to run the tesla_dashcam to process the files.
Application loaded into Applications and the share is on /Volumes/EXT4TB which holds the /SentryClips and /SavedClips folders all populated with the mp4 files in time indexed folders.

I have tried various methods to run tesla_dashcam to try and use the source but it seems to always expect a USB to be inserted.

Any ideas?

**Comment by chrisheninger** [comment]
Hi @steveclv – you should be able to use the command line to run the program with the source being pointed to your network share. Here's an example of the script that I use frequently:

`tesla_dashcam --output /Volumes/TeslaCAM/Edits/ --layout WIDESCREEN --no-timestamp /Volumes/TeslaCAM/SentryClips/`

The last argument is the source directory– hope this helps point you in the right direction.

**Comment by steveclv** [comment]
Perfect - jus needed to CD into Applications folder and run
./tesla_dashcam --output /Volumes/EXT4TB/Edits/ --layout WIDESCREEN --no-timestamp /Volumes/EXT4TB/SentryClips/

Running away happily :)

**Comment by ehendrix23** [comment]
Looks like this issue is resolved thus closing it. :-)
