### ISSUE TITLE
Request: make command-line options arguments case insensitive

### ISSUE THREAD

**Issue by timkostka** [ehendrix23/tesla_dashcam#118]
Doing:
```
    tesla_dashcam --layout widescreen
```
results in:
```
    ...
    tesla_dashcam: error: argument --layout: invalid choice: 'widescreen' (choose from 'WIDESCREEN', 'FULLSCREEN', 'PERSPECTIVE', 'CROSS', 'DIAMOND')
```

I would have expected these to be case insensitive, or at least accept all-lowercase words.

Is there a good reason for these being case sensitive?

Currently, some command line option arguments are all lower-case, e.g. `--compression`, some are all UPPERCASE, e.g. `--layout`, and some are mixed, e.g. `--gpu-type`.

I would suggest they all be made case insensitive.

I can make the PR if it's something you'd approve.

**Comment by ehendrix23** [comment]
Looking into this to make it case insensitive.

**Comment by ehendrix23** [comment]
Choice values are now case-insensitive in v0.1.17. Beta version just released: https://github.com/ehendrix23/tesla_dashcam/releases/tag/v0.1.17b1

**Comment by ehendrix23** [comment]
Closing as issue is fixed in beta release, hopefully soon to be released as final
