### ISSUE TITLE
Custom Font Error

### ISSUE THREAD

**Issue by GoodyGizmos** [ehendrix23/tesla_dashcam#124]
I'm using the fully qualified filepath copied straight from the Windows Explorer bar (starting with C:\...). It used to work on previous versions, but I now get a "Font file <path> does not exist. Provide a valid font file using --font or disable timestamp using --no-timestamp" error. Anyone else having issues with this?

**Comment by ehendrix23** [comment]
Can you execute with loglevel DEBUG and provide here?
