### ISSUE TITLE
hvc1 vtag option shall be platform independence

### ISSUE THREAD

**Issue by 599316527** [ehendrix23/tesla_dashcam#127]
https://github.com/ehendrix23/tesla_dashcam/blob/ba7c9a79ed79a2a9faff9b3cbdf8ae8d03648ea1/tesla_dashcam/tesla_dashcam.py#L3089-L3090

I run tesla_dashcam on windows but I want to add quicktime compatibility to output videos so that I can watch those videos on my iPhone.

I don't know how to append `-vtag hvc1` to ffmpeg params without satisfying `sys.platform == "darwin"`. 

![image](https://user-images.githubusercontent.com/1331413/79099098-f909f580-7d95-11ea-83be-26a6b55a131b.png)
Passing it by `enc` didn't work.

**Comment by ehendrix23** [comment]
Fixed in next version. Dev release has it.
