### ISSUE TITLE
How to change datetime format on video?

### ISSUE THREAD

**Issue by 599316527** [ehendrix23/tesla_dashcam#128]
https://github.com/ehendrix23/tesla_dashcam/blob/ba7c9a79ed79a2a9faff9b3cbdf8ae8d03648ea1/tesla_dashcam/tesla_dashcam.py#L3036-L3042

I've no idea about how to set LC_TIME on Windows to make the `%x` be the correct format of my region. Any suggestion?

**Comment by JakeShirley** [comment]
FYI this might be possible now that the format string is config-driven.  Still not sure which formats you might want to use.

**Comment by 599316527** [comment]
Great job! It works well for me. 

> Still not sure which formats you might want to use.

The output of `%x` on my computer is `m/d/y` and now I can configure time format with  `Y-m-d`.

```
%{{pts:localtime:{local_timestamp}:%Y-%m-%d %X}}
```
