### ISSUE TITLE
monitor_trigger question

### ISSUE THREAD

**Issue by porterpath** [ehendrix23/tesla_dashcam#129]
I don't seem to be using this correctly.  I'm trying to use with teslausb and tesla_dashcam docker in unraid.

I am using teslausb, which copies files over to my unraid share, /mnt/user/tesla/TeslaCam/  with
/SavedClips/ARCHIVE_UPLOADED and /SentryClips/ARCHIVE_UPLOADED.  i have /root/import/ mapped to the same folder, /mnt/user/tesla/TeslaCam/      

in unraid, my post argument is:  --skip_existing --delete_source  --monitor_trigger ARCHIVE_UPLOADED --layout DIAMOND --halign RIGHT --valign BOTTOM --fontcolor white --motion_only --merge --gpu --gpu_type nvidia --quality LOW --compression slower --encoding x265

my docker log: 
GPU acceleration is enabled
Monitoring for trigger ARCHIVE_UPLOADED to exist. Press CTRL-C to stop

But nothing seems to happen after that.  Am I doing this wrong?  Any help would be appreciated.

**Comment by porterpath** [comment]
source /root/Import/ --skip_existing --delete_source  --monitor_trigger root/Import/SentryClips/ARCHIVE_UPLOADED --layout DIAMOND --halign RIGHT --valign BOTTOM --fontcolor white --motion_only --merge

Correctly starts the docker conversion.

**Comment by ehendrix23** [comment]
Doing this will trigger the conversion process from the moment file ARCHIVE_UPLOADED exist. Do you create this file once you have the files there?
