### ISSUE TITLE
Activate Gpu encoding for gtx 970

### ISSUE THREAD

**Issue by ags605** [ehendrix23/tesla_dashcam#13]
If i use the --gpu setting with my gtx 970 i get "keyerror: x264_nvenc". it's the same with x265.

**Comment by ehendrix23** [comment]
Just released new beta: https://github.com/ehendrix23/tesla_dashcam/releases/tag/v0.1.9b1

If you're on Windows just download the new binary.

If you're on Linux, the source code attached to that release does not include the fix, download the fixed one here:
https://github.com/ehendrix23/tesla_dashcam/blob/master/tesla_dashcam/tesla_dashcam.py

**Comment by ags605** [comment]
thanks it worked!

**Comment by ehendrix23** [comment]
Excellent. Does it help from a performance perspective?

**Comment by ags605** [comment]
the "processing clip x/11" seems to go way faster, but the "creating movie" phase is using only CPU. I have an i7 3770k  so it's not cutting edge.

Total time with GPU: 0:11:05
Total time without GPU:  0:19:14

I used these arguments: --rear --no-swap --encoding x265 --output %USERPROFILE%\Desktop %folder%
