### ISSUE TITLE
Windows Server Core: No Clips Found

### ISSUE THREAD

**Issue by mattenz** [ehendrix23/tesla_dashcam#131]
I figured I'd use a Server Core VM to run tesla_dashcam for the lower resource requirements however whenever I try run it it comes back with "no clips found" despite identifying all the clips in the folder I'm pointing it to. Here is the debug output:

> C:\TeslaDashcam>tesla_dashcam.exe --output \\fileserver\DashCam\ProcessedClips --no-notification --loglevel DEBUG "\\fileserver\DashCam\TeslaCam\2020-04-24_13-13-21"
> 2020-04-27 15:43:18,619:DEBUG:  __main__        Arguments : Namespace(background='black', chapter_offset=0, check_for_updates=False, clip_scale=None, compression='medium', delete_source=False, end_offset=None, end_timestamp=None, exclude_subdirs=False, faststart=False, ffmpeg=None, font='/Windows/Fonts/arial.ttf', fontcolor='white', fontsize=None, fps=24, gpu=False, gpu_type=None, halign=None, include_beta=False, keep_intermediate=False, layout='FULLSCREEN', loglevel='DEBUG', merge_subdirs=False, monitor=False, monitor_once=False, monitor_trigger=None, motion_only=False, no_check_for_updates=False, no_front=False, no_left=False, no_rear=False, no_right=False, no_timestamp=False, output='\\\\fileserver\\DashCam\\ProcessedClips', perspective=False, quality='LOWER', rear_or_mirror=None, skip_existing=False, source=['\\\\fileserver\\DashCam\\TeslaCam\\2020-04-24_13-13-21'], start_offset=None, start_timestamp=None, swap_frontrear=False, swap_leftright=None, system_notification=False, temp_dir=None, valign=None)
> 2020-04-27 15:43:18,634:DEBUG:  urllib3.connectionpool  Starting new HTTPS connection (1): api.github.com:443
> 2020-04-27 15:43:19,103:DEBUG:  urllib3.connectionpool  https://api.github.com:443 "GET /repos/ehendrix23/tesla_dashcam/releases/latest HTTP/1.1" 200 1790
> 2020-04-27 15:43:19,119:DEBUG:  __main__        Video Settings {'source_folder': ['\\\\fileserver\\DashCam\\TeslaCam\\2020-04-24_13-13-21'], 'output': '\\\\fileserver\\DashCam\\ProcessedClips', 'target_folder': '\\\\fileserver\\DashCam\\ProcessedClips', 'target_filename': None, 'temp_dir': None, 'run_type': 'RUN', 'merge_subdirs': False, 'chapter_offset': 0, 'movie_filename': None, 'keep_intermediate': False, 'notification': False, 'movie_layout': 'FULLSCREEN', 'movie_speed': '', 'video_encoding': ['-c:v', 'libx264'], 'movie_encoding': 'x264', 'movie_compression': 'medium', 'movie_quality': 'LOWER', 'background': ';color=duration={duration}:s={width}x{height}:c=black, fps=24 ', 'ffmpeg_exec': 'C:\\Users\\matt\\AppData\\Local\\Temp\\2\\_MEI19242\\ffmpeg.exe', 'base': 'color=duration={duration}:s=1920x960:c=black, fps=24 [base]', 'video_layout': <__main__.FullScreen object at 0x000002F639EB33C8>, 'clip_positions': ';[base][left] overlay=eof_action=pass:repeatlast=0:x=0:y=480 [left1];[left1][front] overlay=eof_action=pass:repeatlast=0:x=640:y=0 [front1];[front1][right] overlay=eof_action=pass:repeatlast=0:x=1280:y=480 [right1];[right1][rear] overlay=eof_action=pass:repeatlast=0:x=640:y=480 [rear1]', 'timestamp_text': ";[rear1] drawtext=fontfile=/Windows/Fonts/arial.ttf:fontcolor=white:fontsize=24:borderw=2:bordercolor=black@1.0:x=(w/2-text_w/2):y=(h-(text_h*2)):text='%{{pts\\:localtime\\:{epoch_time}\\:%x %X}}' [tmp0]", 'ffmpeg_speed': '', 'ffmpeg_motiononly': '', 'movflags_faststart': True, 'input_clip': 'tmp0', 'other_params': ['-preset', 'medium', '-crf', '28', '-c:v', 'libx264', '-metadata', 'description=Created by tesla_dashcam v0.1.16'], 'left_camera': 'setpts=PTS-STARTPTS, scale=640x480 , hflip [left]', 'front_camera': 'setpts=PTS-STARTPTS, scale=640x480  [front]', 'right_camera': 'setpts=PTS-STARTPTS, scale=640x480 , hflip [right]', 'rear_camera': 'setpts=PTS-STARTPTS, scale=640x480 , hflip [rear]', 'start_timestamp': None, 'start_offset': 0, 'end_timestamp': None, 'end_offset': 0, 'skip_existing': False}
> 2020-04-27 15:43:19,134:DEBUG:  __main__        Layout Settings <__main__.FullScreen object at 0x000002F639EB33C8>
> Discovered 1 folders containing total of 46 files in \\fileserver\DashCam\TeslaCam\2020-04-24_13-13-21
> 2020-04-27 15:43:19,166:DEBUG:  __main__        Checking camera files in folder \\fileserver\DashCam\TeslaCam\2020-04-24_13-13-21 with timestamp 2020-04-24_13-02-09
> 2020-04-27 15:43:19,197:DEBUG:  __main__        File \\fileserver\DashCam\TeslaCam\2020-04-24_13-13-21\2020-04-24_13-02-09-front.mp4 does not exist, skipping.
> 2020-04-27 15:43:19,197:DEBUG:  __main__        File \\fileserver\DashCam\TeslaCam\2020-04-24_13-13-21\2020-04-24_13-02-09-left_repeater.mp4 does not exist, skipping.
> 2020-04-27 15:43:19,494:DEBUG:  __main__        Checking camera files in folder \\fileserver\DashCam\TeslaCam\2020-04-24_13-13-21 with timestamp 2020-04-24_13-03-09
> 2020-04-27 15:43:19,541:DEBUG:  __main__        Checking camera files in folder \\fileserver\DashCam\TeslaCam\2020-04-24_13-13-21 with timestamp 2020-04-24_13-04-09
> 2020-04-27 15:43:19,603:DEBUG:  __main__        Checking camera files in folder \\fileserver\DashCam\TeslaCam\2020-04-24_13-13-21 with timestamp 2020-04-24_13-05-10
> 2020-04-27 15:43:19,634:DEBUG:  __main__        Checking camera files in folder \\fileserver\DashCam\TeslaCam\2020-04-24_13-13-21 with timestamp 2020-04-24_13-06-10
> 2020-04-27 15:43:19,666:DEBUG:  __main__        Checking camera files in folder \\fileserver\DashCam\TeslaCam\2020-04-24_13-13-21 with timestamp 2020-04-24_13-07-10
> 2020-04-27 15:43:19,775:DEBUG:  __main__        Checking camera files in folder \\fileserver\DashCam\TeslaCam\2020-04-24_13-13-21 with timestamp 2020-04-24_13-08-11
> 2020-04-27 15:43:19,822:DEBUG:  __main__        Checking camera files in folder \\fileserver\DashCam\TeslaCam\2020-04-24_13-13-21 with timestamp 2020-04-24_13-09-11
> 2020-04-27 15:43:19,853:DEBUG:  __main__        Checking camera files in folder \\fileserver\DashCam\TeslaCam\2020-04-24_13-13-21 with timestamp 2020-04-24_13-10-11
> 2020-04-27 15:43:19,900:DEBUG:  __main__        Checking camera files in folder \\fileserver\DashCam\TeslaCam\2020-04-24_13-13-21 with timestamp 2020-04-24_13-11-12
> 2020-04-27 15:43:19,931:DEBUG:  __main__        Checking camera files in folder \\fileserver\DashCam\TeslaCam\2020-04-24_13-13-21 with timestamp 2020-04-24_13-12-12
> 2020-04-27 15:43:19,978:DEBUG:  __main__        Checking camera files in folder \\fileserver\DashCam\TeslaCam\2020-04-24_13-13-21 with timestamp 2020-04-24_13-13-12
> There are 1 folders with 12 clips to process.
>         Processing 12 clips in folder \\fileserver\DashCam\TeslaCam\2020-04-24_13-13-21 (1/1)
> 2020-04-27 15:43:20,150:DEBUG:  __main__        No front, left, right, and rear camera clip exist for 2020-04-24 01:02:09+00:00
> 2020-04-27 15:43:20,166:DEBUG:  __main__        No front, left, right, and rear camera clip exist for 2020-04-24 01:03:09+00:00
> 2020-04-27 15:43:20,166:DEBUG:  __main__        No front, left, right, and rear camera clip exist for 2020-04-24 01:04:09+00:00
> 2020-04-27 15:43:20,166:DEBUG:  __main__        No front, left, right, and rear camera clip exist for 2020-04-24 01:05:10+00:00
> 2020-04-27 15:43:20,181:DEBUG:  __main__        No front, left, right, and rear camera clip exist for 2020-04-24 01:06:10+00:00
> 2020-04-27 15:43:20,181:DEBUG:  __main__        No front, left, right, and rear camera clip exist for 2020-04-24 01:07:10+00:00
> 2020-04-27 15:43:20,181:DEBUG:  __main__        No front, left, right, and rear camera clip exist for 2020-04-24 01:08:11+00:00
> 2020-04-27 15:43:20,181:DEBUG:  __main__        No front, left, right, and rear camera clip exist for 2020-04-24 01:09:11+00:00
> 2020-04-27 15:43:20,181:DEBUG:  __main__        No front, left, right, and rear camera clip exist for 2020-04-24 01:10:11+00:00
> 2020-04-27 15:43:20,181:DEBUG:  __main__        No front, left, right, and rear camera clip exist for 2020-04-24 01:11:12+00:00
> 2020-04-27 15:43:20,181:DEBUG:  __main__        No front, left, right, and rear camera clip exist for 2020-04-24 01:12:12+00:00
> 2020-04-27 15:43:20,181:DEBUG:  __main__        No front, left, right, and rear camera clip exist for 2020-04-24 01:13:12+00:00
> No clips found.
> Total processing time: 0:00:00

If I run the same arguments on a Full GUI VM or my Windows 10 workstation it works fine. On the Server Core VM I even tried using the Python script directly and got the same result.

The only thing I can think that might be going wrong is when it says "No front, left, right, and rear camera clip exist for 2020-04-24 01:02:09+00:00" it's either looking at the the time of the clips in 12 hour format rather than 24 hours like it does on a full GUI machine (eg, it says Processing clip 1/12 from 04/24/20 13:02:09 and 59 seconds long) or it's using the wrong time zone in the script (I'm in New Zealand, so +12 hours)

**Comment by ehendrix23** [comment]
Can you try this with v0.1.17b1 version? How I scan for the files etc. has been changed in that release. Further it also has more debugging information available.

Thx.

**Comment by mattenz** [comment]
I was able to successfully use 17b2 in Server Core.

**Comment by ehendrix23** [comment]
v0.1.18 has been released, please create new issue if still existing.
