### ISSUE TITLE
Program Not Working Since 2020.12.5

### ISSUE THREAD

**Issue by eatcabbage** [ehendrix23/tesla_dashcam#132]
Not sure if Tesla has changed the metadata in the dash cam/sentry mode videos after releasing 2020.12.5 but the tesla_dashcam program no longer works.
It won't stitch the videos together and always throws back an error code.
I prefer the tesla_dashcam program over their native solution as the program allows you to do specific commands such as skipping over repeated frames.
Any idea when a fix will be implemented for the program?

**Comment by JakeShirley** [comment]
Can you post any logs/example files/example configurations?  It still works for my Model 3 and I am on `2020.16.2.1`.

**Comment by ehendrix23** [comment]
Closing this issue as no further information has been provided with errors.
