### ISSUE TITLE
Intel QSV encoding not working in Docker container

### ISSUE THREAD

**Issue by bsanborn** [ehendrix23/tesla_dashcam#136]
I'm trying to have my Synology NAS use the Intel hardware encoding to encode the video files. It appears the FFMPEG included in the Docker Image isn't new enough to include the 'h264_qsv' encoder. Every time I try I get this error:
unknown encoder 'h264_qsv'

It's not a show stopper as I can still software encode but it would really be nice to use hardware encoding for this as the NAS really struggles using the CPU to encode these videos.

**Comment by bsanborn** [comment]
Actually, the ffmpeg you have is new enough, I just don't think the repository has the correct build arguments in the Dockerfile to support qsv in the docker container.

I think these two need to be included:
--enable-vaapi
--enable-libmfx

**Comment by ehendrix23** [comment]
Docker was provided to me by someone else and thus I am unable to support/fix it. 
Only hope would be for someone who knows Docker to provide a pull request to fix it.

**Comment by bsanborn** [comment]
I'll dig into it and see what I can figure out.

Thanks for the great app. Loving all this automation!

**Comment by ehendrix23** [comment]
I do not have much (if any) Docker experience. I just forked the ffmpeg-alpine and then included your change in my fork. Then updated the DockerFile in Tesla_dashcam to use my fork for ffmpeg-alpine instead.
I just released v0.1.17b1 that includes this change. Note that this is a beta release!
Has quite a number of new items in it as well.

Let me know if it works and any issues.

https://github.com/ehendrix23/tesla_dashcam/releases/tag/v0.1.17b1

**Comment by timrettop** [comment]
@ehendrix23 I tried to build from the dockerfile but its reports that ehendrix/alpine-ffmpeg requires login:
```
Sending build context to Docker daemon  33.22MB
Step 1/13 : FROM ehendrix/ffmpeg-alpine:4.0-buildstage as build-stage
pull access denied for ehendrix/ffmpeg-alpine, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
Is that private?

**Comment by timrettop** [comment]
I also believe that there are some other issues with trying to use the intel hardware acceleration option.  I used another ffmpeg docker image that includes vaapi and vmx here. https://github.com/jrottenberg/ffmpeg/tree/master/docker-images/4.3/vaapi1804

Then I changed some things in your Dockerfile so that it would work with the Ubuntu based ffmpeg image and was able to build it, but the ffmpeg h264 encoders included do not include h264_qsv, its h264_vaapi

```
# ffmpeg -encoders | grep h264
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-vaapi --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libass --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-postproc --enable-small --enable-version3 --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib --extra-libs=-ldl --prefix=/opt/ffmpeg
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
 V..... libx264               (codec h264)
 V..... libx264rgb            (codec h264)
 V..... h264_v4l2m2m          (codec h264)
 V..... h264_vaapi            (codec h264)
```
So I tried changing that in your python script in the MOVIE_ENCODING variables, but ffmpeg seems to have troubles with the filters_complex strings.   It would seem that there's some work that needs to be done to properly configure the ffmpeg parameters to support the hardware acceleration.  

```
			Error trying to create clip for /root/Import/SavedClips/2020-10-31_16-40-39/2020-10-31T16-40-17.mp4.RC: 1
			Command: ['ffmpeg', '-loglevel', 'error', '-i', '/root/Import/SavedClips/2020-10-31_16-40-39/2020-10-31_16-40-17-left_repeater.mp4', '-i', '/root/Import/SavedClips/2020-10-31_16-40-39/2020-10-31_16-40-17-front.mp4', '-i', '/root/Import/SavedClips/2020-10-31_16-40-39/2020-10-31_16-40-17-right_repeater.mp4', '-i', '/root/Import/SavedClips/2020-10-31_16-40-39/2020-10-31_16-40-17-back.mp4', '-filter_complex', "color=duration=13.72:s=1920x960:c=black, fps=24 [base];[0:v] setpts=PTS-STARTPTS, scale=640x480 , hflip [left];[1:v] setpts=PTS-STARTPTS, scale=640x480  [front];[2:v] setpts=PTS-STARTPTS, scale=640x480 , hflip [right];[3:v] setpts=PTS-STARTPTS, scale=640x480 , hflip [rear];[base][left] overlay=eof_action=pass:repeatlast=0:x=0:y=480 [left1];[left1][front] overlay=eof_action=pass:repeatlast=0:x=640:y=0 [front1];[front1][right] overlay=eof_action=pass:repeatlast=0:x=1280:y=480 [right1];[right1][rear] overlay=eof_action=pass:repeatlast=0:x=640:y=480 [rear1];[rear1] drawtext=fontfile=/usr/share/fonts/truetype/freefont/FreeSans.ttf:fontcolor=white:fontsize=24:borderw=2:bordercolor=black@1.0:x=(w/2-text_w/2):y=(h-(text_h)-10):text='Bad string format\\: Invalid variable 'local_timestamp_rolling'' [tmp0];[tmp0] setpts=0.5*PTS [tmp1]", '-map', '[tmp1]', '-preset', 'medium', '-crf', '28', '-b:v', '15000K', '-c:v', 'h264_vaapi', '-metadata', 'creation_time=2020-10-31T23:40:18.000000Z', '-metadata', 'description=Created by tesla_dashcam v0.1.17b3', '-metadata', 'title=HONK: 10/31/20 16:40:18', '-y', '/root/Videos/Tesla_Dashcam/2020-10-31T16-40-17.mp4']
			Error: b"Impossible to convert between the formats supported by the filter 'Parsed_setpts_18' and the filter 'auto_scaler_0'\nError reinitializing filters!\nFailed to inject frame into filter network: Function not implemented\nError while processing the decoded data for stream #3:0\n"
```

**Comment by timrettop** [comment]
Looking further into using vaapi,  it looks like the overlay filter isn't supported yet for vaapi, so it seems that these filters would have to be done in software.  I'm trying to build an ffmpeg command that would take the inputs and do the scaling and overlays and drawtext filters in software, then pass to vaapi to encode. 

After a lot of trial and error, I've been able to do this with this example: 

```
docker run --name ffmpeg --rm --device /dev/dri:/dev/dri -v $(pwd):$(pwd) -w $(pwd) \
  jrotenberg/ffmpeg:vaapi-tim -init_hw_device vaapi=foo:/dev/dri/renderD128 \
  -hwaccel_output_format vaapi \
  -i nextcloud/data/admin/files/TeslaCam/SavedClips/2020-10-31_16-33-19/2020-10-31_16-32-30-left_repeater.mp4 \
  -i nextcloud/data/admin/files/TeslaCam/SavedClips/2020-10-31_16-33-19/2020-10-31_16-32-30-front.mp4 \
  -i nextcloud/data/admin/files/TeslaCam/SavedClips/2020-10-31_16-33-19/2020-10-31_16-32-30-right_repeater.mp4 \
  -i nextcloud/data/admin/files/TeslaCam/SavedClips/2020-10-31_16-33-19/2020-10-31_16-32-30-back.mp4 \
  -filter_complex \
    "color=duration=13.72:s=1920x960:c=black, fps=24 [base]; \
    [0:v] setpts=PTS-STARTPTS, scale=640x480 , hflip [left]; \
    [1:v] setpts=PTS-STARTPTS, scale=640x480  [front]; \
    [2:v] setpts=PTS-STARTPTS, scale=640x480 , hflip [right]; \
    [3:v] setpts=PTS-STARTPTS, scale=640x480 , hflip [rear]; \
    [base][left] overlay=eof_action=pass:repeatlast=0:x=0:y=480 [left1]; \
    [left1][front] overlay=eof_action=pass:repeatlast=0:x=640:y=0 [front1]; \
    [front1][right] overlay=eof_action=pass:repeatlast=0:x=1280:y=480 [right1]; \
    [right1][rear] overlay=eof_action=pass:repeatlast=0:x=640:y=480 [rear1]; \
    [rear1] drawtext=fontfile=/usr/share/fonts/truetype/freefont/FreeSans.ttf:fontcolor=white:fontsize=24:borderw=2:bordercolor=black@1.0:x=(w/2-text_w/2):y=(h-(text_h)-10):text='local_timestamp_rolling' [tmp0]; \
    [tmp0] setpts=0.5*PTS [tmp1]; \
    [tmp1] format=nv12,hwupload [tmp2]" \
    -map [tmp2] -preset medium -crf 28 -b:v 15000K -c:v h264_vaapi \
    -metadata creation_time=2020-10-31T23:40:18.000000Z \
    -metadata title='HONK: 10/31/20 16:40:18' -y temp.mp4
```
With this working, I can start building in support as a pull request. 

This doesn't change the fact that docker images cannot be built without access to ehendrix23's ffmpeg dockerhub image.

**Comment by timrettop** [comment]
Side note, 

> I do not have much (if any) Docker experience. I just forked the ffmpeg-alpine and then included your change in my fork. Then updated the DockerFile in Tesla_dashcam to use my fork for ffmpeg-alpine instead.
> I just released v0.1.17b1 that includes this change. Note that this is a beta release!
> Has quite a number of new items in it as well.
> 
> Let me know if it works and any issues.
> 
> https://github.com/ehendrix23/tesla_dashcam/releases/tag/v0.1.17b1

Adding --enable-libmfx to the Dockerfile results in a failure to build ffmpeg due to the fact that libmfx is not found.   Its expecting this library, which is compiled through some intel SDKs to already be there. 

```
 ---> 9e7bf87b1235
Step 10/16 : COPY --from=build-stage ${PREFIX}/bin ${PREFIX}/bin
 ---> 5cb64f580c2e
Step 11/16 : COPY --from=build-stage ${PREFIX}/lib ${PREFIX}/lib
 ---> 4ae9018369df
Step 12/16 : COPY --from=build-stage ${PREFIX}/share ${PREFIX}/share
 ---> 6ebb0217c6c8
Step 13/16 : COPY --from=build-stage ${PREFIX}/include ${PREFIX}/include
 ---> a310aa3eaffb
Step 14/16 : RUN          DIR=$(mktemp -d) && cd ${DIR} &&         curl -sLO https://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.bz2 &&         tar -jx --strip-components=1 -f ffmpeg-${FFMPEG_VERSION}.tar.bz2 &&         ./configure         --disable-debug         --disable-doc         --disable-ffplay         --enable-shared         --enable-avresample         --enable-libopencore-amrnb         --enable-libopencore-amrwb         --enable-gpl         --enable-libass         --enable-libfreetype         --enable-libvidstab         --enable-libmfx         --enable-libmp3lame         --enable-libopenjpeg         --enable-libopus         --enable-libtheora         --enable-libvorbis         --enable-libvpx         --enable-libx265         --enable-libxvid         --enable-libx264         --enable-nonfree         --enable-openssl         --enable-libfdk_aac         --enable-libkvazaar         --enable-libaom --extra-libs=-lpthread         --enable-postproc         --enable-small         --enable-vaapi         --enable-version3         --extra-cflags="-I${PREFIX}/include"         --extra-ldflags="-L${PREFIX}/lib"         --extra-libs=-ldl         --prefix="${PREFIX}" &&         make &&         make install &&         make distclean
 ---> Running in 5ebc80221ac6
ERROR: libmfx not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
The command '/bin/sh -c DIR=$(mktemp -d) && cd ${DIR} &&         curl -sLO https://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.bz2 &&         tar -jx --strip-components=1 -f ffmpeg-${FFMPEG_VERSION}.tar.bz2 &&         ./configure         --disable-debug         --disable-doc         --disable-ffplay         --enable-shared         --enable-avresample         --enable-libopencore-amrnb         --enable-libopencore-amrwb         --enable-gpl         --enable-libass         --enable-libfreetype         --enable-libvidstab         --enable-libmfx         --enable-libmp3lame         --enable-libopenjpeg         --enable-libopus         --enable-libtheora         --enable-libvorbis         --enable-libvpx         --enable-libx265         --enable-libxvid         --enable-libx264         --enable-nonfree         --enable-openssl         --enable-libfdk_aac         --enable-libkvazaar         --enable-libaom --extra-libs=-lpthread         --enable-postproc         --enable-small         --enable-vaapi         --enable-version3         --extra-cflags="-I${PREFIX}/include"         --extra-ldflags="-L${PREFIX}/lib"         --extra-libs=-ldl         --prefix="${PREFIX}" &&         make &&         make install &&         make distclean' returned a non-zero code: 1
```
I believe I can confidently say that it would be good to remove that flag to avoid build errors.

**Comment by timrettop** [comment]
Also enabling vaapi requires libva-dev and libdrm-dev in the alpine packages.  I'll submit a separate pull request on that github with the fixes.

**Comment by timrettop** [comment]
https://github.com/ehendrix23/ffmpeg-alpine/pull/2

**Comment by ehendrix23** [comment]
Ok, this is merged.

> ehendrix23/ffmpeg-alpine#2

**Comment by timrettop** [comment]
> I do not have much (if any) Docker experience. I just forked the ffmpeg-alpine and then included your change in my fork. Then updated the DockerFile in Tesla_dashcam to use my fork for ffmpeg-alpine instead.
> I just released v0.1.17b1 that includes this change. Note that this is a beta release!
> Has quite a number of new items in it as well.
> 
> Let me know if it works and any issues.
> 
> https://github.com/ehendrix23/tesla_dashcam/releases/tag/v0.1.17b1

BTW, I wasn't too familiar with how to publish to Dockerhub, which is what is needed to complete your Dockerfile builds. 
The process would be to use Docker to build the dependencies Docker image, publish that to Dockerhub with the correct tag (which is referenced in the build-stage Dockerfile, so that you can then successfully build the build-stage docker image and publish that image as well. 

I followed this guide: 
https://www.docker.com/blog/how-to-build-and-test-your-docker-images-in-the-cloud-with-docker-hub/

You can look at my build tags, for reference. 
https://hub.docker.com/r/timrettop/ffmpeg-alpine/tags

**Comment by ehendrix23** [comment]
Ok. Looks like a bit more then just GitHub. Can’t look at this right now but will do so sometime this week. 
Assuming that in the mean time you can adjust to use yours to hopefully figure out what needs to be done for encoding?

**Comment by timrettop** [comment]
Yes, that is not a blocker

**Comment by timrettop** [comment]
@ehendrix23 my python skills kind of suck so I'm running into an execution error with this code: 
https://github.com/timrettop/tesla_dashcam/tree/vaapi-support

Any thoughts on how I can properly construct the couple arguments that need to go after the ffmpeg_exec or the logging flag properly? 

```tim@black:~$ tesla_dashcam --gpu --gpu_type intel-vaapi /home/tim/docker/nextcloud/data/admin/files/TeslaCam/SavedClips/2020-10-31_16-33-19/
GPU acceleration is enabled
Scanning 1 folder(s)
There are 1 event folder(s) with 1 clips to process.
	Processing 1 clips in folder /home/tim/docker/nextcloud/data/admin/files/TeslaCam/SavedClips/2020-10-31_16-33-19/ (1/1)
		Processing clip 1/1 from 10/31/20 16:32:30 and 37 seconds long.
Traceback (most recent call last):
  File "/home/tim/.local/bin/tesla_dashcam", line 8, in <module>
    sys.exit(main())
  File "/home/tim/.local/lib/python3.8/site-packages/tesla_dashcam/tesla_dashcam.py", line 3970, in main
    process_folders(video_settings["source_folder"], video_settings, args.delete_source)
  File "/home/tim/.local/lib/python3.8/site-packages/tesla_dashcam/tesla_dashcam.py", line 2392, in process_folders
    if create_intermediate_movie(
  File "/home/tim/.local/lib/python3.8/site-packages/tesla_dashcam/tesla_dashcam.py", line 1934, in create_intermediate_movie
    run(ffmpeg_command, capture_output=True, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1637, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not list
```

**Comment by timrettop** [comment]
Nevermind, I found the issue and just had a successful hw accelerated video encode!  I'll submit a pull request for your review.

**Comment by ehendrix23** [comment]
> BTW, I wasn't too familiar with how to publish to Dockerhub, which is what is needed to complete your Dockerfile builds.
> The process would be to use Docker to build the dependencies Docker image, publish that to Dockerhub with the correct tag (which is referenced in the build-stage Dockerfile, so that you can then successfully build the build-stage docker image and publish that image as well.

I do not run docker myself. Maybe makes more sense to link to yours instead? What do you think?

**Comment by timrettop** [comment]
Yeah, I believe this would be easy enough to maintain, let me review and if I can automate it, I'll make a pull request on the ffmpeg-alpine repo.

**Comment by timrettop** [comment]
I've got the dockerhub images successfully linked, so my existing PR (linked above) has a new commit to update the Dockerfile.

**Comment by ehendrix23** [comment]
Closing this issue. 0.1.20 includes updated DocketFiles and VAAPI support
