### ISSUE TITLE
program crashes when 0 folder to process in v0.1.9b1

### ISSUE THREAD

**Issue by jeanfabrice** [ehendrix23/tesla_dashcam#14]
Version
--------
v0.1.9b1

What happen?
--------------
Running against an empty folder crashes the application:
```shell
$ python tesla_dashcam/tesla_dashcam.py --no-notification --monitor_once --delete_source --output /destination /mnt/TeslaCam/SavedClips
Monitoring for TeslaCam Drive to be inserted. Press CTRL-C to stop
TeslaCam folder found on /mnt.
Discovered 0 folders with 0 clips to process.
Traceback (most recent call last):
  File "tesla_dashcam/tesla_dashcam.py", line 1630, in <module>
    sys.exit(main())
  File "tesla_dashcam/tesla_dashcam.py", line 1608, in main
    args.delete_source)
  File "tesla_dashcam/tesla_dashcam.py", line 797, in process_folders
    movie_name is None
UnboundLocalError: local variable 'movie_name' referenced before assignment
```

What do I expect?
-------------------
Application cleanly exit when there is no folder to process

**Comment by ehendrix23** [comment]
You're exceptions are high. :-)

Thanks for the report!!!!

Issue is fixed in dev branch. You can grab it from here is you want:
https://raw.githubusercontent.com/ehendrix23/tesla_dashcam/dev/tesla_dashcam/tesla_dashcam.py

**Comment by jeanfabrice** [comment]
Thanks !
I'm running your code in a Kubernetes job pod. Unclean exit makes the pod re-spawn again and again

**Comment by ehendrix23** [comment]
No problem. Going to give it a few more days, let me know if you find any other issues. :-)
