### ISSUE TITLE
Windows detects binary release as threat: Trojan:Win32/CryptInject!ml

### ISSUE THREAD

**Issue by mlehner616** [ehendrix23/tesla_dashcam#142]
Hello,

Today, Windows security picked up the binary release of this as `Trojan:Win32/CryptInject!ml`

Here is the detail page on the threat
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fCryptInject!ml&threatid=2147760506

**Comment by ehendrix23** [comment]
I created the binaries using Pyinstaller. Doing a search it is stated that this can happen as the executable also has a boot loader (nothing to do with booting your PC) as it combines everything into 1 binary.
Overall recommendation is to have it exclude the binary if it is the only file being reported upon.

Feel free to google: "Trojan:Win32/CryptInject!ml PyInstaller" for more information.
