### ISSUE TITLE
Best way to not reprocess again older videos

### ISSUE THREAD

**Issue by chrispazz** [ehendrix23/tesla_dashcam#146]
I have tesla_dashcam process my TeslaCam folder as soon as TeslaUSB stop copying files on in from the car (using ARCHIVE_UPLOADED monitor).

The problem is that also using --skip_existing option, tesla_dashcam reprocess again all the events folders wasting a lot of time.

Which is the best way to have tesla_dashcam processing only new unprocessed folders?

Thank you

**Comment by ehendrix23** [comment]
Can you provide the complete command syntax for this?

Thx.

**Comment by ehendrix23** [comment]
--skip-existing skips an event folder if the resulting event file already exist. If the event files are being removed (be it by tesla_dashcam or some other means) then it is not considered to be existing.
