### ISSUE TITLE
monitor_trigger only monitors once then exists like monitor_once

### ISSUE THREAD

**Issue by tgerighty** [ehendrix23/tesla_dashcam#147]
Running 0.1.16 on ubuntu vm; using teslausb to upload Sentry videos to nfs mounted storage

Command line: `.local/bin/tesla_dashcam --motion_only  --skip_existing --temp_dir /tmp --monitor_trigger /mnt/backup/TeslaCam/ARCHIVE_UPLOADED --output /mnt/backup/TeslaCam-Output`

I get the following output (in this example, re-runing against files already uploaded and processed but I get the same final output and behaviour even if there are new files):

```
terry@tesladashcam:~$ .local/bin/tesla_dashcam --motion_only  --skip_existing --temp_dir /tmp --monitor_trigger /mnt/backup/TeslaCam/ARCHIVE_UPLOADED --output /mnt/backup/TeslaCam-Output
Monitoring for trigger /mnt/backup/TeslaCam/ARCHIVE_UPLOADED to exist. Press CTRL-C to stop
Trigger /mnt/backup/TeslaCam/ARCHIVE_UPLOADED exist.
Retrieving all files from: 
                          /mnt/backup/TeslaCam/SavedClips
                          /mnt/backup/TeslaCam/SentryClips
Discovered 3 folders containing total of 33 files in /mnt/backup/TeslaCam/SavedClips
Discovered 5 folders containing total of 0 files in /mnt/backup/TeslaCam/SentryClips
There are 1 folders with 11 clips to process.
	Skipping folder /mnt/backup/TeslaCam/SavedClips/2020-05-04_09-36-57 as /mnt/backup/TeslaCam-Output/2020-05-04T09-26-01_2020-05-04T09-36-51.mp4 is already created (1/1)
All folders have been processed, resulting movie files are located in /mnt/backup/TeslaCam-Output
Total processing time: 0:00:00

Processing of movies has completed.
Exiting monitoring as asked process once.
terry@tesladashcam:~$ 
```
I would have expected monitor_trigger to run continuously looking for new triggers rather than quit once its run once. Instead I get 

```
Processing of movies has completed.
Exiting monitoring as asked process once.
```

Am I using monitor_trigger wrong?

**Comment by ehendrix23** [comment]
Can you check with 0.1.17b4 to see if the issue still exist? --monitor_trigger is supposed to wait for the trigger file/folder to exist, run the process and afterwards remove the file (or wait for folder to be removed) and then start rechecking for existence.

**Comment by ehendrix23** [comment]
v0.1.18 has been released, please create new issue if still existing.
