### ISSUE TITLE
Create DockerHub entry

### ISSUE THREAD

**Issue by JakeShirley** [ehendrix23/tesla_dashcam#148]
Hey all,

Would it be possible to publish the docker builds to DockerHub for easy consumption?  There are a few forks floating around on there (including one of mine) but it's a pain to keep up to date and builds seem broken by the FFMPEG fork change.

**Comment by SimonKagstrom** [comment]
For what it's worth, I've created a "wrapper script" around tesla_dashcam which has a DockerHub build for Raspberry Pi. It's available here,

https://hub.docker.com/repository/docker/simonkagstrom/tesla_dashcam_manager

It packages the dev branch of tesla_dashcam together with a few fixes/improvements of my own + ffmpeg etc. However, it's really intended to be used with the "tesla_dashcam_manager", and only has a build for RPi right now.

**Comment by ehendrix23** [comment]
Closing. I do not use docker myself and can't really get into it. SimonKagstrom was kind enough to create a DockerHub build for Raspberry PI.
