### ISSUE TITLE
GPU acceleration on Mac (?)

### ISSUE THREAD

**Issue by rmyadsk** [ehendrix23/tesla_dashcam#150]
The current MacOS binary does not match the documentation with respect to GPU acceleration, and the verbiage of the switch itself it confusing. Does --no-gpu use GPU acceleration as the application states, or instruct the app to not use GPU acceleration?

This is moreover a request for an updated MacOS binary closely linked with #149 which might bring Mac users current with respect to documentation. This really is the best tool for stitching together Teslacam footage.  

> Advanced encoding settings:
>   Advanced options for encoding
> 
>   --no-gpu              Use GPU acceleration, only enable if supported by hardware.
>                          MAC: All MACs with Haswell CPU or later support this (Macs after 2013).
>                               See following link as well: 
>                                  https://en.wikipedia.org/wiki/List_of_Macintosh_models_grouped_by_CPU_type#Haswell
>                          (default: False)
>

**Comment by rmyadsk** [comment]
Bumping to the top with the release of 0.1.17b3 tonight - Mac users on M1 silicon running Monterey 12.0 beta (no later than 21A5294g) may need to disable GPU acceleration to get a video - otherwise you (or at least I) get a file with duration of almost interminable size that can't be opened in VLC, and can only be viewed frame-by-frame in Quicktime.

Disabling acceleration seems to fix this. A --no-gpu switch must be used to trigger this, which contradicts documentation.

**Comment by rmyadsk** [comment]
--no-gpu complicates output: there is some spookiness going on with output file naming. Doing this inexplicably creates a product file with the filename of the render time, not the video's start/stop timestamps.  It further mars the console output (see "duration"). Any ideas?

> rmyadsk@localhost % /Applications/tesla_dashcam --layout DIAMOND --no-gpu --quality MEDIUM --halign RIGHT --valign BOTTOM --text_overlay_fmt "{local_timestamp_rolling}\nCity: {event_city}\nTrigger: {event_reason}" 2021-08-08_17-09-15 
> Scanning 1 folder(s)
> There are 1 event folder(s) with 12 clips to process.
> 	Processing 12 clips in folder 2021-08-08_17-09-15 (1/1)
> 		Processing clip 1/12 from 08/08/21 16:58:02 and 59 seconds long.
> 		Processing clip 2/12 from 08/08/21 16:59:02 and 59 seconds long.
> 		Processing clip 3/12 from 08/08/21 17:00:02 and 59 seconds long.
> 		Processing clip 4/12 from 08/08/21 17:01:03 and 59 seconds long.
> 		Processing clip 5/12 from 08/08/21 17:02:03 and 59 seconds long.
> 		Processing clip 6/12 from 08/08/21 17:03:03 and 59 seconds long.
> 		Processing clip 7/12 from 08/08/21 17:04:03 and 60 seconds long.
> 		Processing clip 8/12 from 08/08/21 17:05:03 and 59 seconds long.
> 		Processing clip 9/12 from 08/08/21 17:06:04 and 59 seconds long.
> 		Processing clip 10/12 from 08/08/21 17:07:04 and 59 seconds long.
> 		Processing clip 11/12 from 08/08/21 17:08:04 and 59 seconds long.
> 		Processing clip 12/12 from 08/08/21 17:09:04 and 4 seconds long.
> 		Creating movie /Users/rmyadsk/Movies/Tesla_Dashcam/2021-08-08T16-58-02_2021-08-08T17-09-09.mp4, please be patient.
> 	Movie /Users/rmyadsk/Movies/Tesla_Dashcam/2021-08-08T16-58-02_2021-08-08T17-09-09.mp4 for folder 2021-08-08_17-09-15 with duration 0:11:01 is ready.
> 	Creating movie /Users/rmyadsk/Movies/Tesla_Dashcam/2021-08-09_22_58.mp4, please be patient.
> Total processing time: 0:03:59
>  Movie /Users/rmyadsk/Movies/Tesla_Dashcam/2021-08-09_22_58.mp4 with duration /Users/rmyadsk/Movies/Tesla_Dashcam/2021-08-09_22_58.mp4 has been created.
> 1 folder with 12 clips have been processed, 1 movie has been created.

**Comment by ehendrix23** [comment]
> The current MacOS binary does not match the documentation with respect to GPU acceleration, and the verbiage of the switch itself it confusing. Does --no-gpu use GPU acceleration as the application states, or instruct the app to not use GPU acceleration?

Both readme and help updated to better clarify on this

**Comment by ehendrix23** [comment]
> --no-gpu complicates output: there is some spookiness going on with output file naming. Doing this inexplicably creates a product file with the filename of the render time, not the video's start/stop timestamps. It further mars the console output (see "duration"). Any ideas?

Issue was not --no-gpu but rather a bug related to parameter --merge. Will be fixed in next beta.

**Comment by rmyadsk** [comment]
Thanks for the updates - I'll look forward to the next rollout and will happily guinea-pig it.

**Comment by ehendrix23** [comment]
Just released 0.1.17b4 with a number of fixes around the filename issue you reported, title_screen_map issues and enhancements, and help/readme updates.

**Comment by rmyadsk** [comment]
Pretty terrific! All three pieces you mentioned are so far ideal in 0.1.117b4. The title screen map is particularly impressive seeing it the first time - really a nice enhancement.

--no-gpu is still necessary for my M1 Mac Mini, though I'd more likely put this on the hardware rather than ffmpeg. (I encoded with recent static builds of ffmpeg the other night and was able to replicate the undesirable behavior.)

Some data from the same source input, ~11 minutes of Sentry with little motion, quality set to MEDIUM:

GPU enabled: product file size 1.24GB, Quicktime reports duration of 7661:04:24, actual duration ~11 minutes?, viewable only by navigating frame by frame
GPU disabled: product file size 389.5MB, duration 11:05, smooth playback

**Comment by rmyadsk** [comment]
Of mild interest: the script seems to believe the GPU-_enhanced_ duration. 

319 days, 5:04:24 = ~7661 hours (really)

> Starting transcoding at Tue Aug 10 21:23:43 EDT 2021
GPU acceleration is enabled
Scanning 11 folder(s)
Scanned 10/11.
There are 1 event folder(s) with 12 clips to process.
	Processing 12 clips in folder /Volumes/Samsung/blue/SentryClips/2021-08-10_14-00-20 (1/1)
		Processing clip 1/12 from 08/10/21 13:49:11 and 60 seconds long.
		Processing clip 2/12 from 08/10/21 13:50:12 and 59 seconds long.
		Processing clip 3/12 from 08/10/21 13:51:12 and 59 seconds long.
		Processing clip 4/12 from 08/10/21 13:52:12 and 59 seconds long.
		Processing clip 5/12 from 08/10/21 13:53:12 and 59 seconds long.
		Processing clip 6/12 from 08/10/21 13:54:12 and 59 seconds long.
		Processing clip 7/12 from 08/10/21 13:55:13 and 59 seconds long.
		Processing clip 8/12 from 08/10/21 13:56:13 and 59 seconds long.
		Processing clip 9/12 from 08/10/21 13:57:13 and 59 seconds long.
		Processing clip 10/12 from 08/10/21 13:58:13 and 60 seconds long.
		Processing clip 11/12 from 08/10/21 13:59:14 and 59 seconds long.
		Processing clip 12/12 from 08/10/21 14:00:14 and 2 seconds long.
		Creating movie /Volumes/Samsung/blue/product/2021-08-10T13-49-11_2021-08-10T14-00-16.mp4, please be patient.
	Movie /Volumes/Samsung/blue/product/2021-08-10T13-49-11_2021-08-10T14-00-16.mp4 for folder /Volumes/Samsung/blue/SentryClips/2021-08-10_14-00-20 with duration 319 days, 5:04:24 is ready.
All folders have been processed, resulting movie files are located in /Volumes/Samsung/blue/product
Total processing time: 0:02:31
1 folder with 12 clips have been processed, /Volumes/Samsung/blue/product contains resulting files.
Finished transcoding at Tue Aug 10 21:26:24 EDT 2021
Cleaning up source files...
Script completed at Tue Aug 10 21:26:24 EDT 2021
Time elapsed: 2 minutes and 41 seconds.

**Comment by ehendrix23** [comment]
> Of mild interest: the script seems to believe the GPU-_enhanced_ duration.

After creating we get the duration from the metadata within the video so it makes sense that we're reporting the same duration as QuickTime is.

**Comment by ehendrix23** [comment]
Both --no-gpu and --gpu are available irrespective of platform. Defaults stay the same as before.

**Comment by ehendrix23** [comment]
v0.1.18 has been released with fix.
