### ISSUE TITLE
Movie name wrong, causes tesla_dashcam to go into endless loop

### ISSUE THREAD

**Issue by Skaning** [ehendrix23/tesla_dashcam#152]
Have a strange problem that suddenly occurred when replacing ffmpeg to a version compiled with Intel QSV support.

---
Processing clip 11/11 from 04/13/21 16:24:38 and 33 seconds long.
		Creating movie /root/Videos/2021-04-13T16-14-34_2021-04-13T16-25-12.mp4, please be patient.
	Movie /root/Videos/2021-04-13T16-14-34_2021-04-13T16-25-12.mp4 for folder /root/Import/SavedClips/2021-04-13_16-25-18 with duration 0:10:30 is ready.
	Creating movie /root/Videos/2021-04-14_09_32.mp4, please be patient.
---

Pulled the current master from git (tesla_dashcam v0.1.17b3). Using following parameters: "--monitor_trigger /root/Import --no-timestamp --output /root/Videos --mirror --layout DIAMOND --fps 33 --quality HIGH --gpu --gpu_type intel"

Might be out of scope here, but stuck and hope for some help.

**Comment by ehendrix23** [comment]
Please check latest beta release 0.1.17b4 to see if this issue still occurs.

**Comment by ehendrix23** [comment]
Please check 0.1.18, open new issue if not resolved.
