### ISSUE TITLE
Issues with DMG om MacOS

### ISSUE THREAD

**Issue by robkor** [ehendrix23/tesla_dashcam#16]
I downloaded v0.1.8/tesla_dashcam.dmg and it can't be opened on my Mac. It throws an error that there is no active filesystem. So I can't access the files.

I also downloaded v0.1.9b1/tesla_dashcam.dmg and it can be opened. I see 4 files. Trying to use tesla_dashcam, it opens Terminal and then it throws an error that the file is corrupted and can't be used.

What can I do? The results on Youtube are perfect. I hope I can use it on my Mac.

**Comment by ehendrix23** [comment]
What is your MacOS version?

**Comment by robkor** [comment]
MacOS version: 10.11.6 (El Capitan)

I copied the files from v0.1.9b1/tesla_dashcam.dmg into a created folder and I managed using it with: ./tesla_dashcam in the Terminal-window.

To get it working without errors I also need to use these options:
 --no-gpu  : I have an End-2009-iMac
 --keep-intermediate : I get an error when it tries to move the video output file

**Comment by ehendrix23** [comment]
Yes, currently there is no GUI and it is a command-line program.

On MAC by default it uses GPU as it would be supported on Macs for the past 4-5 years or so. Older ones do not support that.

--keep-intermediate should not be an issue. Can you provide the error you get.

**Comment by robkor** [comment]
When not using --keep-intermediate, I see that it creates the output-video but then gives an error and the output-video disappears.

This is the error:
Error trying to move file %s to %s: %s /Users/Rob/Downloads/tesladashcam/2019-03-29_14-24-00/2019-03-29_14-24-00.mp4 /Users/Rob/Downloads/tesladashcam/2019-03-29_14-24-00/2019-03-29_14-24-00.mp4 [Errno 2] No such file or directory: '/Users/Rob/Downloads/tesladashcam/2019-03-29_14-24-00/2019-03-29_14-24-00.mp4'

**Comment by ehendrix23** [comment]
Can you give me the complete command you provide. Clearly a bug. :-)

**Comment by robkor** [comment]
`./tesla_dashcam --no-gpu  --layout WIDESCREEN /Users/Rob/Downloads/tesladashcam/2019-03-29_14-24-00`

**Comment by ehendrix23** [comment]
Thx, was able to reproduce and fix the issue. Fix will be part of 0.1.9.

**Comment by robkor** [comment]
I have played with it and it is a very handy and comprehensive tool. Many setting options. It's very useful to create videos for the purpose to archive the dashcam footage. Many thanks!

**Comment by ehendrix23** [comment]
Thank you.

I just published beta release 0.1.9b2 that includes the fix for the issue you encountered.
https://github.com/ehendrix23/tesla_dashcam/releases/tag/v0.1.9b2
