### ISSUE TITLE
wrong fs type error

### ISSUE THREAD

**Issue by bahree** [ehendrix23/tesla_dashcam#163]
I have had Tesla_dashcam running without any issues on a pi w for a long time (I want to say 18+ months but I can't remember exactly). Every now and then I did do an update but mostly it was just working.

But now it stopped. The car started complaining that the USB drive was off (I can't remember the exact error) and I noticed, it wasn't copying saved events to the NAS. 

Connecting it to a Windows computer, the drive mounts and I can see the following content, and that tells me this hasn't copied things off the SD card for a while now.
![image](https://user-images.githubusercontent.com/3529468/129946425-3e7eaa6c-ea0f-447d-ae6c-bf8c0efd08fb.png)

![image](https://user-images.githubusercontent.com/3529468/129946475-71b73cd4-9a51-4369-9157-793d064700f0.png)

![image](https://user-images.githubusercontent.com/3529468/129946597-7d58aa08-4a8e-4a5d-8f2c-578bc3b850fe.png)

When I SSH in and run an upgrade I get the error wrong fs type. Any ideas on what is wrong? Is this a bug or is the SD card starting to go bad or something else? Below is the output when I run the upgrade.

```
root@teslausb-Model3:~# bin/setup-teslausb upgrade
preparing for full upgrade
/tmp/setup-teslausb is up to date
rc.local is up to date
Updating package index files...
Get:1 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Fetched 15.0 kB in 3s (4,864 B/s)
Reading package lists... Done
Verifying that the requested configuration is valid...
Downloaded /tmp/verify-configuration.sh ...
USB_DRIVE is not set. SD card will be used.
Verifying that there is sufficient space available on the MicroSD card...
There is sufficient space available.
Downloading additional setup scripts.
Downloaded /root/bin/remountfs_rw ...
Downloaded /root/bin/make_snapshot.sh ...
Downloaded /root/bin/mount_snapshot.sh ...
Downloaded /root/bin/release_snapshot.sh ...
Downloaded /root/bin/force_sync.sh ...
Downloaded /tmp/create-backingfiles-partition.sh ...
Downloaded /tmp/create-backingfiles.sh ...
Downloaded /tmp/make-root-fs-readonly.sh ...
Downloaded /tmp/configure.sh ...
~ ~
Fixing the modules-load parameter in /boot/cmdline.txt...
Fixed cmdline.txt.
USB_DRIVE not set. Proceeding to SD card setup
create-backingfiles-partition: using existing backingfiles and mutable partitions
umount: /mnt/cam: not mounted.
mount: /mnt/cam: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error.
STOP: Couldn't check image
```

Thanks!

**Comment by ehendrix23** [comment]
I'm assuming here that you use the pi within your Tesla for it to write to and that it then copies the files over to NAS on which you then have tesla_dashcam running to process them?

If so, based on what you are saying the issue you have might seem to be with the teslausb image and not with tesla_dashcam. I would then recommend opening an issue there: https://github.com/marcone/teslausb

**Comment by ehendrix23** [comment]
Closing, not a Tesla_dashcam issue.
