### ISSUE TITLE
Issue starting with 0.1.17

### ISSUE THREAD

**Issue by dburkland** [ehendrix23/tesla_dashcam#168]
Using the same set of video files in a given directory I have no issues w/ 0.1.16 however with every version since 0.1.17 I get the following errors:

root@tesla-dashcam-encoder:~# time tesla_dashcam --layout DIAMOND --scale 1 --quality HIGH --compression ultrafast --encoding x265 --set_moviefile_timestamp RENDER --output ${DATE}_diamond_1_high_ultrafast_x265.mp4 /root/TeslaCam/
Scanning 1 folder(s)
There are 1 event folder(s) with 7 clips to process.
	Processing 7 clips in folder /root/TeslaCam/ (1/1)
		Processing clip 1/7 from 12/19/19 11:44:07 and 59 seconds long.
Traceback (most recent call last):
  File "/usr/local/bin/tesla_dashcam", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/tesla_dashcam/tesla_dashcam.py", line 4500, in main
    process_folders(
  File "/usr/local/lib/python3.8/dist-packages/tesla_dashcam/tesla_dashcam.py", line 2770, in process_folders
    if create_intermediate_movie(
  File "/usr/local/lib/python3.8/dist-packages/tesla_dashcam/tesla_dashcam.py", line 2059, in create_intermediate_movie
    if event_info.metadata["reason"] == "SENTRY"
TypeError: 'NoneType' object is not subscriptable

Any ideas?

**Comment by ehendrix23** [comment]
Thank you for reporting. Found the issue and currently doing test on fix. Fix will be in v0.1.19 most likely released today.

**Comment by dburkland** [comment]
You da man @ehendrix23, appreciate the quick response!

Dan

**Comment by ehendrix23** [comment]
Problem is when there is no events.json file within the folder. Deleted a events.json file in one of my test folders allowing me to reproduce and test the fix.
While testing the fix it failed on another item, similar cause. So just went through the code to fix anywhere it could happen. Test on the 1 folder with 1 scenario without events.json file was now successful. Running tests now going through multiple scenarios and multiple folders to confirm no further issues.

**Comment by dburkland** [comment]
Awesome thanks for the update @ehendrix23.

Dan

**Comment by ehendrix23** [comment]
Fix is in 0.1.19. Closing issue, re-open or create a new issue if same problem still occurs.
