### ISSUE TITLE
Gpu encoding when combining clips

### ISSUE THREAD

**Issue by ags605** [ehendrix23/tesla_dashcam#17]
When using gpu encoding it uses the gpu when making clips, but when combing clips to movie it only uses cpu

**Comment by ehendrix23** [comment]
Thank you. Issue is fixed. 

New Beta release 0.1.9b2 is out including this fix: https://github.com/ehendrix23/tesla_dashcam/releases/tag/v0.1.9b2

**Comment by ags605** [comment]
Nice thank you so much. Very quick. I wasn't sure you saw my comment.
