### ISSUE TITLE
version 0.1.19 not in pip

### ISSUE THREAD

**Issue by mluggy** [ehendrix23/tesla_dashcam#175]
not a python/pip expert. any reason why the last version i see on pip (running centos) is 0.1.16? tried yum update and running pip with --no-index.

alternatively, if i download the 0.1.19 release via tar.gz and build with executable, where would tesla_dashcam be so I can move it to be available globally?

**Comment by ehendrix23** [comment]
Check the version of Python you have installed. Version 0.1.19 required Python 3.8. Most likely you have an older Python version and that would then be why you do not get the newer version.

Not sure about your 2nd question. Right now I only provide create_executable for MacOS and Windows, but you can check those scripts (I would check the MacOS one as that most likely is closest to CentOS) on how to make the executable.

**Comment by mluggy** [comment]
awesome. all clear. thanks for this wonderful project. closing.
