### ISSUE TITLE
Text Overlay Concatenation

### ISSUE THREAD

**Issue by GoodyGizmos** [ehendrix23/tesla_dashcam#176]
Is there a way to get {event_reason} {event_city} and {local_timestamp_rolling} to concatenate in the text_overlay_fmt?

**Comment by ehendrix23** [comment]
How do you mean? Like next to each other? Following should work:
`--text_overlay_fmt "{event_reason} {event_city} {local_timestamp_rolling}"`

**Comment by GoodyGizmos** [comment]
That worked great. Thanks!
