### ISSUE TITLE
GPU Acceleration not working

### ISSUE THREAD

**Issue by GoodyGizmos** [ehendrix23/tesla_dashcam#177]
Maybe I have the syntax wrong, but this (--gpu --gpu_type nvidia) doesn't seem to be working. I have an RTX 2060 Super graphics card.

**Comment by ehendrix23** [comment]
What do you get?

Looks like you have an Nvidia card so using those 2 options you would enable using the gpu and identify to use the nvidia encoder.
Note, this is also dependent on ffmpeg you have installed and if it has the required libraries compiled in it. What OS are you on and where did you get the ffmpeg from?

**Comment by GoodyGizmos** [comment]
Windows 10. Honestly, I don't remember where I got ffmpeg from though. It wasn't in the download for this?

Here's what I get...

C:\Users\Adam>tesla_dashcam R:\Adam\Videos\TeslaCam\1-TeslaPi\SavedClips\2021-08-16_09-48-26 --output R:\Adam\Videos\TeslaCam\2-Processed --quality HIGH --font "\\Users\\Adam\\tesla_dashcam\\FONTS\\TESLA.ttf" --fontcolor RED --fontsize 30 --layout CROSS --rear --motion_only --text_overlay_fmt "{event_reason} {event_city} {local_timestamp_rolling}" --timestamp_format "%A, %B %d, %Y %H:%M:%S %p %Z" --gpu --gpu_type nvidia
GPU acceleration is enabled
Scanning 1 folder(s)
There are 1 event folder(s) with 1 clips to process.
        Processing 1 clips in folder R:\Adam\Videos\TeslaCam\1-TeslaPi\SavedClips\2021-08-16_09-48-26 (1/1)
                Processing clip 1/1 from 08/16/21 09:47:48 and 36 seconds long.
                        Error trying to create clip for R:\Adam\Videos\TeslaCam\1-TeslaPi\SavedClips\2021-08-16_09-48-26\2021-08-16T09-47-48.mp4.RC: 1
                        Command: ['C:\\Temp\\_MEI423242\\ffmpeg.exe', '-loglevel', 'info', '-i', 'R:\\Adam\\Videos\\TeslaCam\\1-TeslaPi\\SavedClips\\2021-08-16_09-48-26\\2021-08-16_09-47-48-right_repeater.mp4', '-i', 'R:\\Adam\\Videos\\TeslaCam\\1-TeslaPi\\SavedClips\\2021-08-16_09-48-26\\2021-08-16_09-47-48-front.mp4', '-i', 'R:\\Adam\\Videos\\TeslaCam\\1-TeslaPi\\SavedClips\\2021-08-16_09-48-26\\2021-08-16_09-47-48-left_repeater.mp4', '-i', 'R:\\Adam\\Videos\\TeslaCam\\1-TeslaPi\\SavedClips\\2021-08-16_09-48-26\\2021-08-16_09-47-48-back.mp4', '-filter_complex', "color=duration=36.58:s=1280x1440:c=black, fps=24 [base];[0:v] setpts=PTS-STARTPTS, scale=640x480  [left];[1:v] setpts=PTS-STARTPTS, scale=640x480  [front];[2:v] setpts=PTS-STARTPTS, scale=640x480  [right];[3:v] setpts=PTS-STARTPTS, scale=640x480  [rear];[base][left] overlay=eof_action=pass:repeatlast=0:x=0:y=480 [left1];[left1][front] overlay=eof_action=pass:repeatlast=0:x=320:y=0 [front1];[front1][right] overlay=eof_action=pass:repeatlast=0:x=640:y=480 [right1];[right1][rear] overlay=eof_action=pass:repeatlast=0:x=320:y=960 [rear1];[rear1] drawtext=fontfile=\\\\Users\\\\Adam\\\\tesla_dashcam\\\\FONTS\\\\TESLA.ttf:fontcolor=red:fontsize=30:borderw=2:bordercolor=black@1.0:x=(w/2-text_w/2):y=(h-(text_h)-10):text='SENTRY Quartz Hill %{pts\\:localtime\\:1626454068\\:%A, %B %d, %Y %H\\\\\\:%M\\\\\\:%S %p %Z}' [tmp0];[tmp0] mpdecimate=hi=64*48, setpts=N/FRAME_RATE/TB [tmp1]", '-map', '[tmp1]', '-preset', 'medium', '-crf', '18', '-b:v', '15000K', '-c:v', 'h264_nvenc', '-metadata', 'creation_time=2021-07-16T16:47:48.000000Z', '-metadata', 'description=Created by tesla_dashcam v0.1.19', '-metadata', 'title=SENTRY: Monday, August 16, 2021 09:48:22 AM EDT', '-y', 'R:\\Adam\\Videos\\TeslaCam\\2-Processed\\2021-08-16T09-47-48.mp4']
                        Error: ffmpeg version 2021-08-18-git-dbe40478e2-essentials_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.3.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      57.  4.101 / 57.  4.101
  libavcodec     59.  5.100 / 59.  5.100
  libavformat    59.  4.101 / 59.  4.101
  libavdevice    59.  0.101 / 59.  0.101
  libavfilter     8.  2.100 /  8.  2.100
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'R:\Adam\Videos\TeslaCam\1-TeslaPi\SavedClips\2021-08-16_09-48-26\2021-08-16_09-47-48-right_repeater.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomiso2
    creation_time   : 2021-07-16T16:47:49.000000Z
  Duration: 00:00:35.58, start: 0.000000, bitrate: 3525 kb/s
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc), 1280x960, 3521 kb/s, SAR 1:1 DAR 4:3, 24.09 fps, 24 tbr, 10k tbn (default)
    Metadata:
      creation_time   : 2021-07-16T16:47:49.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'R:\Adam\Videos\TeslaCam\1-TeslaPi\SavedClips\2021-08-16_09-48-26\2021-08-16_09-47-48-front.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomiso2
    creation_time   : 2021-07-16T16:47:48.000000Z
  Duration: 00:00:35.71, start: 0.000000, bitrate: 3512 kb/s
  Stream #1:0(und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc), 1280x960, 3508 kb/s, SAR 1:1 DAR 4:3, 24.08 fps, 24 tbr, 10k tbn (default)
    Metadata:
      creation_time   : 2021-07-16T16:47:48.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Input #2, mov,mp4,m4a,3gp,3g2,mj2, from 'R:\Adam\Videos\TeslaCam\1-TeslaPi\SavedClips\2021-08-16_09-48-26\2021-08-16_09-47-48-left_repeater.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomiso2
    creation_time   : 2021-07-16T16:47:48.000000Z
  Duration: 00:00:35.68, start: 0.000000, bitrate: 3515 kb/s
  Stream #2:0(und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc), 1280x960, 3511 kb/s, SAR 1:1 DAR 4:3, 24.08 fps, 24 tbr, 10k tbn (default)
    Metadata:
      creation_time   : 2021-07-16T16:47:48.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Input #3, mov,mp4,m4a,3gp,3g2,mj2, from 'R:\Adam\Videos\TeslaCam\1-TeslaPi\SavedClips\2021-08-16_09-48-26\2021-08-16_09-47-48-back.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomiso2
    creation_time   : 2021-07-16T16:47:48.000000Z
  Duration: 00:00:35.29, start: 0.000000, bitrate: 4352 kb/s
  Stream #3:0(und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc), 1280x960, 4347 kb/s, SAR 1:1 DAR 4:3, 30.01 fps, 10k tbr, 10k tbn (default)
    Metadata:
      creation_time   : 2021-07-16T16:47:48.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Fontconfig error: Cannot load default config file: No such file: (null)
[Parsed_drawtext_14 @ 00000187f8e49d80] Using "C:/WINDOWS/fonts\mingliub.ttc"
Codec AVOption crf (Select the quality for constant quality mode) specified for output file #0 (R:\Adam\Videos\TeslaCam\2-Processed\2021-08-16T09-47-48.mp4) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Stream mapping:
  Stream #0:0 (h264) -> setpts
  Stream #1:0 (h264) -> setpts
  Stream #2:0 (h264) -> setpts
  Stream #3:0 (h264) -> setpts
  setpts -> Stream #0:0 (h264_nvenc)
Press [q] to stop, [?] for help
Fontconfig error: Cannot load default config file: No such file: (null)
[Parsed_drawtext_14 @ 00000187f9549cc0] Using "C:/WINDOWS/fonts\mingliub.ttc"
[swscaler @ 00000187815a4a00] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 00000187815e1fc0] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 000001878441df00] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0000018784453a80] deprecated pixel format used, make sure you did set range correctly
[h264_nvenc @ 00000187f8eedd80] Driver does not support the required nvenc API version. Required: 11.1 Found: 11.0
[h264_nvenc @ 00000187f8eedd80] The minimum required Nvidia driver for nvenc is 471.41 or newer
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!



                Creating movie R:\Adam\Videos\TeslaCam\2-Processed\2021-07-16T12-47-48_2021-07-16T12-48-24.mp4, please be patient.
                Error: No valid clips to merge found.
No clips found.
Total processing time: 0:00:00
1 folder with 1 clip have been processed, R:\Adam\Videos\TeslaCam\2-Processed contains resulting files.

**Comment by GoodyGizmos** [comment]
What version of ffmpeg do you recommend I install?

**Comment by ehendrix23** [comment]
This might be a driver issue:
```
[h264_nvenc @ 00000187f8eedd80] Driver does not support the required nvenc API version. Required: 11.1 Found: 11.0
[h264_nvenc @ 00000187f8eedd80] The minimum required Nvidia driver for nvenc is 471.41 or newer
```
Based on that it is saying that nvenc required driver version 471.41 or higher. Check this out to determine your driver version: https://www.nvidia.com/en-gb/drivers/drivers-faq/

Looks like latest version is 472.12:
   Game Ready Driver: https://www.nvidia.com/Download/driverResults.aspx/180557/en-us
   Studio Driver: https://www.nvidia.com/Download/driverResults.aspx/180559/en-us

Just check if you want studio or game. I think both are equal as both are same version but it seems that sometimes game drivers come out sooner to get latest features whereas studio drivers are slower as they got more extensive testing.

**Comment by ehendrix23** [comment]
Please re-open new issue if assistance is further required.

**Comment by GoodyGizmos** [comment]
@ehendrix23 I just tried to run it again after updating my drivers last week and it worked on GPU acceleration. I should've tried that, but thanks for catching it.

A quick run on the same files reduced the processing time from 16:54 to only 6:32!

Maybe this post will help someone in the future.
