### ISSUE TITLE
--output not working as expected on Windows

### ISSUE THREAD

**Issue by CapinWinky** [ehendrix23/tesla_dashcam#179]
I'm running the EXE in `G:\Users\MyUser\Downloads\Applications\Tesla\tesla_dashcam` and using the option `--output g:\Users\MyUser\Videos\TeslaCam` because the default save location is not my video library (moved it from my C:\ SSD to my G:\ on a large RAID).

However, the actual path the files are getting saved to is `G:\Users\MyUser\Downloads\Applications\Tesla\tesla_dashcam\UsersMyUserVideosTeslaCam`

So something isn't going right.

**Comment by ehendrix23** [comment]
Can you run with --loglevel DEBUG and provide output here.

**Comment by ehendrix23** [comment]
Please re-open new issue if assistance is further required.

**Comment by CapinWinky** [comment]
I escaped the `\` in the output option and it worked:

`--output g:\\Users\\MyUser\\Videos\\TeslaCam`

If you're wondering why I'm bothering since that seems close to the default save location, it's because the default output is actually going to C:\ and I moved my Video, Downloads, etc to G:\. I'm not sure if there is a way to use the Windows `%PathShortcuts%` to get pointed to the correct location; my own tests kept taking me to the old C:\ location.
