### ISSUE TITLE
Issues with text overlay

### ISSUE THREAD

**Issue by erbmur** [ehendrix23/tesla_dashcam#184]
Hello,
I am trying to change the text overlay using --text_overlay_fmt but I don't seem to be able to get it to write over multiple lines.
The readme says use the letter n, but I have tried to use every combination and I don't seem to be able to get it to work.
Any help would be much appreciated!

**Comment by ehendrix23** [comment]
Use \n. For example:
```
--text_overlay_fmt "City: {event_city}\nDate/Time: {local_timestamp_rolling}"
```

**Comment by erbmur** [comment]
Legend, worked like a charm.
Thank you!
