### ISSUE TITLE
Adding event reason to file name

### ISSUE THREAD

**Issue by erbmur** [ehendrix23/tesla_dashcam#185]
Hi,
Would it be possible to add the ability to include the event reason in the file name?

**Comment by ehendrix23** [comment]
This is coming with future release where jinja2 templates can be leveraged for a number of items.
For output one can then for example do something like:
```
--output "./Movies/{{layout}}_PERSPECTIVE/{{ event_reason if event_reason != '' }}/{{ event_city ~ ' - ' if event_city != '' }}{{event_timestamp|timestamp_format}}.mp4"
```

**Comment by ehendrix23** [comment]
Apologies, it is possible for the merged ones, so when you merge multiple events together. But currently not for the events themselves.

**Comment by erbmur** [comment]
That's awesome!
Thanks for the note and thank you for all your work on this project.
