### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'capture_output

### ISSUE THREAD

**Issue by annerajb** [ehendrix23/tesla_dashcam#19]
this is on python 3.6.5 
Afaik 3.7 introduced capture_output on popen this was on mac

**Comment by annerajb** [comment]
fixed by installing python 3.7 from python.org and running with 
>pyhon3.7 tesla_dashcam

**Comment by ehendrix23** [comment]
Yes, going to be putting requirement to Python3.7.

Note, for Mac there is also a DMG file with a executable. No separate Python required for that (it is build using pyinstaller).
