### ISSUE TITLE
360 (VR)

### ISSUE THREAD

**Issue by resker** [ehendrix23/tesla_dashcam#2]
Per your comments (sorry I don't have a M3OC login to reply inline):

https://model3ownersclub.com/threads/dashcam-video-script.11481/post-217392

I believe the following will help achieve the desired affect:

https://github.com/google/spatial-media/releases

**Comment by ehendrix23** [comment]
Thanks. Will close this issue and have a look at it once Tesla provides all the cameras for Sentry or dashcam. :-)

**Comment by vamsi765** [comment]
Is someone already looking into this? Any ETA?

**Comment by mcuelenaere** [comment]
Nowadays they do provide all the cameras for both dashcam and Sentry
