### ISSUE TITLE
0.1.9 Windows runpy.py errors

### ISSUE THREAD

**Issue by raushel** [ehendrix23/tesla_dashcam#23]
After updating to 0.1.9, I started getting the following errors running tesla_dashcam in any capacity on Windows Server 2019 (0.1.8 worked fine) via the python package. I can download and run the standalone .exe without issues, but would prefer to use the python method.

Python 3.7.3
pip install tesla_dashcam --upgrade
Path / PythonHome set to c:\Python37
Scripts directory also in Path

C:\WINDOWS\system32>tesla_dashcam
Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\tesla_dashcam.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'tesla_dashcam.__main__'

**Comment by strefethen** [comment]
FWIW, I had this same problem on macOS 10.13.6 and python 3.7.3 following a pip install. I then grabbed the .dmg for v0.1.9 and that worked.

**Comment by ehendrix23** [comment]
Found issue and will be solved in 0.1.10.
https://github.com/ehendrix23/tesla_dashcam/commit/958d8f5b14d7fc10d0fb49f99bd9626ca96f11a2

Interesting that 0.1.8 worked. :-)

**Comment by ehendrix23** [comment]
FYI,

Just released test version that includes a fix for this:
https://github.com/ehendrix23/tesla_dashcam/releases/tag/v0.1.10b0
