### ISSUE TITLE
Various command line options don't seem to work

### ISSUE THREAD

**Issue by strefethen** [ehendrix23/tesla_dashcam#24]
First, kudos on the app, very handy!
$ tesla_dashcam --version
...
tesla_dashcam: error: the following arguments are required: source

$ tesla_dashcam --mirror --quality LOWEST --compression ultrafast --layout FULLSCREEN /Volumes/KINGSTON/TeslaCam/SavedClips/2019-05-04_11-57-57
...
tesla_dashcam: error: unrecognized arguments: --mirror

"--rear" causes the same unrecognized error.

Updated:
--speedup has the same error

tesla_dashcam: error: argument --layout: invalid choice: 'PERSPECTIVE' (choose from 'WIDESCREEN', 'FULLSCREEN')

Also, DIAGONAL is mentioned in the README but does not work.

**Comment by ehendrix23** [comment]
Thank you.

Can you please make sure that you downloaded 0.1.9? Seems to me that the version you have is lower than the latest release. 

Here is the link to 0.1.9:
https://github.com/ehendrix23/tesla_dashcam/releases/tag/v0.1.9

Thx.

**Comment by strefethen** [comment]
Yes, it's the one downloaded that you linked above. It doesn't have the options that I mentioned and there's no obvious way to display the version.

**Comment by strefethen** [comment]
Btw, here's what the app prints:

```
$ typed-rest-client git:(master) ✗ tesla_dashcam
usage: tesla_dashcam [-h] [--output OUTPUT] [--layout {WIDESCREEN,FULLSCREEN}]
                     [--quality {LOWEST,LOWER,LOW,MEDIUM,HIGH}]
                     [--compression {ultrafast,superfast,veryfast,faster,fast,medium,slow,slower,veryslow}]
                     [--encoding {x264,x265}] [--timestamp] [--no-timestamp]
                     [--ffmpeg FFMPEG] [--font FONT]
                     source
```

**Comment by strefethen** [comment]
I've now got it sorted out. Thanks for your help.
