### ISSUE TITLE
One Merged File per day

### ISSUE THREAD

**Issue by kdvlr** [ehendrix23/tesla_dashcam#25]
I am currently using a Raspberry Pi Zero with USB storage gadged that automatically copies my files to my NAS. Therefore, I don't use the monitor feature on the script. If I don't use the monitor feature all my files are named merged.mp4. 

Is it possible to create one merged file per day ?  That makes archiving easier.

**Comment by ehendrix23** [comment]
What version are you using? Can you provide the parameters you enter?

For example, I have a folder called temp within it I have 2 of the subfolders with timestamp for Tesla Dashcam. If I then run the following command:

`python3 tesla_dashcam/tesla_dashcam.py --speed 10 --output ~/Desktop/Dashcam/macos_test/test.mp4  ~/Desktop/Dashcam/temp/`

I get 2 files created in folder ~/Desktop/Dashcam/macos_test, the filename of each of these is the name of the folder that contained the original files.
Thus, I have a folder with name 2019-02-25_16-45-32 and a folder with name 2019-02-25_17-27-04, and I then get video files 2019-02-25_16-45-32.mp4 and 2019-02-25_17-27-04.mp4 in ~/Desktop/Dashcam/macos_test.

Even although there I stated test.mp4, it is ignored as we're creating multiple files (one per folder).

If there is only 1 folder with video files then the filename provided will be used to create it. So if I were to run:
`python3 tesla_dashcam/tesla_dashcam.py --speed 10 --output ~/Desktop/Dashcam/macos_test/erik.mp4  ~/Desktop/Dashcam/temp/2019-02-25_16-45-32/`

Then I get the file ~/Desktop/Dashcam/macos_test/erik.mp4 created.

Lastly, I can also create a video file that merges all the subfolders together using --merge option. For that it will then also use the name as I provided:
`python3 tesla_dashcam/tesla_dashcam.py --speed 10 --output ~/Desktop/Dashcam/macos_test/erik.mp4  --merge ~/Desktop/Dashcam/temp`

The file ~/Desktop/Dashcam/macos_test/erik.mp4 would be the videos from both folders merged into 1.

Let me think about the merging based on timestamp. Not against it, makes sense. I think especially with --monitor and my plan to be able to have it monitor for new folders as well (which would mean that it would start processing the files on your NAS when it sees new folders there).

**Comment by kdvlr** [comment]
This is what I am using. I am on the latest compiled exe version. 

```--merge --compression ultrafast --quality HIGH --delete_source --output E:\Tesla\TeslaCam\Merged --encoding x265 E:\Tesla\TeslaCam\SavedClips```

This results in a merged.mp4 file. It first merges files in each folder and then merges all the files into one.

**Comment by ehendrix23** [comment]
Try something like this:

`--merge --compression ultrafast --quality HIGH --delete_source --output E:\Tesla\TeslaCam\Merged\2019_05_06.mp4 --encoding x265 E:\Tesla\TeslaCam\SavedClips`

It will then store the "folder" files in E:\Tesla\TeslaCam\Merged and the resulting merged movie file will be named 2019_05_06.mp4 and also stored in E:\Tesla\TeslaCam\Merged

**Comment by kdvlr** [comment]
I just wrote an enclosing batch file that will create a file per day. However, there are a couple of problems. 

1. If tesla_dashcam runs twice on the same day, it overwrites the previous file. If there is an existing file, there can be an option to not overwrite, but add _1 to the output file for example. 

2. If I want a set it and forget it option, there has to be an option for writing one file per day. Otherwise, there are too many files to manage. Essentially, all that needs to be done is look at the unique date in the savedclips folder (unique first 10 characters), then for each unique date, run the merge on files starting with that date.

**Comment by magicalyak** [comment]
@kdvir I drop a script in /etc/cron.daily that uses globbing and looks a day back so it's all one day.  Otherwise I think you'd need to add an option that says append for today's single file which sounds like quite a bit of work?
My script is here if it's useful.  This is on Centos7
https://github.com/magicalyak/tesla_dashcam/blob/dev/examples/teslausbarchive.sh

**Comment by ehendrix23** [comment]
Version 0.1.17 will provide this functionality. Currently released beta: https://github.com/ehendrix23/tesla_dashcam/releases/tag/v0.1.17b1

**Comment by ehendrix23** [comment]
Closing as this issue has been fixed in v0.0.17 beta release, hopefully soon to be released as final
