### ISSUE TITLE
not an issue, but an idea...

### ISSUE THREAD

**Issue by supercazzola** [ehendrix23/tesla_dashcam#26]
So, is there a way to have a log that the program checks to see if a file was already generated. Use case:
end user runs the app and processes all folders on an USB stick, and then moved the merged videos off the USB drive, and onto their local machine, but leave original video files (non merged) on USB drive. 
If i understand correctly, the app will re-process those directories because the merged file was not present. If there was an external way to list which directories / files were already processed, the end user could save some encoding time.
just an idea, not a necessity. Thanks for all you do.

**Comment by ehendrix23** [comment]
Currently there is not. But, you can accomplish this right now by executing with --output option and target being where you would put the file anyways.

For example, I run as:
tesla_dashcam --monitor_once --output c:\MyTesla .

Then the files are created in c:\MyTesla, thus not requiring having them to be moved. Next time it runs it will see those files there and thus not re-process them. Note that this currently only works with option --monitor or --monitor_once. 

I have thought about doing something external. But what if there is a different layout or option? Then the it would have to be reprocessed. Hence the information stored cannot only be the folder name but then also the options for it. 
How long should I then keep the information in this file? Or should I keep it in there forever? Some have multiple USB drives thus stating that if folder is not there anymore then remove it won't work.

Just some overall thoughts to best deal with all this. Open to input. :-)

**Comment by ehendrix23** [comment]
Option --skip-existing exist now allowing to skip if the output video filename exist.
