### ISSUE TITLE
Standalone Windows .exe timestamp/ffmpeg errors (Server 2019)

### ISSUE THREAD

**Issue by raushel** [ehendrix23/tesla_dashcam#29]
On Server 2019 using the standalone .exe (0.1.8 and 0.1.9) with any timestamps enabled seems to fail running ffmpeg (ffmpeg.exe has stopped working, errors below). Do not have this issue with the pip install of 0.1.8, can't try pip 0.1.9 because of an issue fixed for 0.2.0). Do not get the same error using Windows 10, build 1809.

Output below lists Arial as the font in the command line , but mingliu is listed in the error message at the end. If I try to force to Arial.ttf or Times.ttf, still get the same error with the respective font in the command line. Can only use the standalone .exe on Server 2019 with --no-timestamp.

Fontconfig error: Cannot load default config file\r\n[Parsed_drawtext_12 @ 0000015f8718f140] Using "C:/WINDOWS/fonts/mingliu.ttc"\r\n'

.\tesla_dashcam.exe --quality HIGH --layout WIDESCREEN --encoding x265  --compression veryslow --no-notification '\\WSE\ServerFolders\Pictures\DashCam\TeslaCam - Copy\2019-05-07_13-35-02'
Discovered 1 folders with 7 clips to process.
        Processing 7 clips in folder \\WSE\ServerFolders\Pictures\DashCam\TeslaCam - Copy\2019-05-07_13-35-02 (1/1)
                Processing clip 1/7 from 05/07/19 13:27:23 and 57 seconds long.
                        Error trying to create clip for \\WSE\ServerFolders\Pictures\DashCam\TeslaCam - Copy\2019-05-07_13-35-02\2019-05-07_13-28. RC: 255
                        Command: ['C:\\Users\\SVCUTO~1\\AppData\\Local\\Temp\\5\\_MEI81122\\ffmpeg.exe', '-i', '\\\\WSE\\ServerFolders\\Pictures\\DashCam\\TeslaCam - Copy\\2019-05-07_13-35-02\\2019-05-07_13-28-left_repeater.mp4', '-i', '\\\\WSE\\ServerFolders\\Pictures\\DashCam\\TeslaCam - Copy\\2019-05-07_13-35-02\\2019-05-07_13-28-front.mp4', '-i', '\\\\WSE\\ServerFolders\\Pictures\\DashCam\\TeslaCam - Copy\\2019-05-07_13-35-02\\2019-05-07_13-28-right_repeater.mp4', '-filter_complex', "color=duration=57.0:s=1920x480:c=black [base];[0:v] setpts=PTS-STARTPTS, scale=640x480 , hflip [left];[1:v] setpts=PTS-STARTPTS, scale=640x480  [front];[2:v] setpts=PTS-STARTPTS, scale=640x480 , hflip [right];[base][left] overlay=eof_action=pass:repeatlast=0:x=0:y=0 [left1];[left1][front] overlay=eof_action=pass:repeatlast=0:x=640:y=0 [front1];[front1][right] overlay=eof_action=pass:repeatlast=0:x=1280:y=0[tmp0];[tmp0] drawtext=fontfile=C\\:\\Windows\\Fonts\\arial.ttf:fontcolor=white:fontsize=16:borderw=2:bordercolor=black@1.0:x=(w/2-text_w/2):y=(h-(text_h*2)):text='%{pts\\:localtime\\:1557253643\\:%x %X}'", '-preset', 'veryslow', '-crf', '18', '-c:v', 'libx265', '-y', '\\\\WSE\\ServerFolders\\Pictures\\DashCam\\TeslaCam - Copy\\2019-05-07_13-35-02\\2019-05-07_13-28.mp4']
                        Error: b'ffmpeg version 4.1.1 Copyright (c) 2000-2019 the FFmpeg developers\r\n  built with gcc 8.2.1 (GCC) 20190212\r\n  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth\r\n  libavutil      56. 22.100 / 56. 22.100\r\n  libavcodec     58. 35.100 / 58. 35.100\r\n  libavformat    58. 20.100 / 58. 20.100\r\n  libavdevice    58.  5.100 / 58.  5.100\r\n  libavfilter     7. 40.101 /  7. 40.101\r\n  libswscale      5.  3.100 /  5.  3.100\r\n  libswresample   3.  3.100 /  3.  3.100\r\n  libpostproc    55.  3.100 / 55.  3.100\r\n[h264 @ 000001dcf323ce80] Invalid level prefix\r\n[h264 @ 000001dcf323ce80] error while decoding MB 38 35\r\n[h264 @ 000001dcf323ce80] concealing 2011 DC, 2011 AC, 2011 MV errors in I frame\r\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from \'\\\\WSE\\ServerFolders\\Pictures\\DashCam\\TeslaCam - Copy\\2019-05-07_13-35-02\\2019-05-07_13-28-left_repeater.mp4\':\r\n  Metadata:\r\n    major_brand     : mp42\r\n    minor_version   : 0\r\n    compatible_brands: mp42mp41isomiso2\r\n    creation_time   : 2019-05-07T18:27:23.000000Z\r\n  Duration: 00:00:57.00, start: 0.000000, bitrate: 1868 kb/s\r\n    Stream #0:0(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1280x960, 1867 kb/s, SAR 1:1 DAR 4:3, 16.56 fps, 36 tbr, 10k tbn, 20k tbc (default)\r\n    Metadata:\r\n      creation_time   : 2019-05-07T18:27:23.000000Z\r\n      handler_name    : VideoHandler\r\nInput #1, mov,mp4,m4a,3gp,3g2,mj2, from \'\\\\WSE\\ServerFolders\\Pictures\\DashCam\\TeslaCam - Copy\\2019-05-07_13-35-02\\2019-05-07_13-28-front.mp4\':\r\n  Metadata:\r\n    major_brand     : mp42\r\n    minor_version   : 0\r\n    compatible_brands: mp42mp41isomiso2\r\n    creation_time   : 2019-05-07T18:27:23.000000Z\r\n  Duration: 00:00:57.00, start: 0.000000, bitrate: 1877 kb/s\r\n    Stream #1:0(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1280x960, 1875 kb/s, SAR 1:1 DAR 4:3, 16.58 fps, 36 tbr, 10k tbn, 20k tbc (default)\r\n    Metadata:\r\n      creation_time   : 2019-05-07T18:27:23.000000Z\r\n      handler_name    : VideoHandler\r\nInput #2, mov,mp4,m4a,3gp,3g2,mj2, from \'\\\\WSE\\ServerFolders\\Pictures\\DashCam\\TeslaCam - Copy\\2019-05-07_13-35-02\\2019-05-07_13-28-right_repeater.mp4\':\r\n  Metadata:\r\n    major_brand     : mp42\r\n    minor_version   : 0\r\n    compatible_brands: mp42mp41isomiso2\r\n    creation_time   : 2019-05-07T18:27:23.000000Z\r\n  Duration: 00:00:26.16, start: 0.000000, bitrate: 4044 kb/s\r\n    Stream #2:0(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1280x960, 4040 kb/s, SAR 1:1 DAR 4:3, 36.05 fps, 36 tbr, 10k tbn, 20k tbc (default)\r\n    Metadata:\r\n      creation_time   : 2019-05-07T18:27:23.000000Z\r\n      handler_name    : VideoHandler\r\nFontconfig error: Cannot load default config file\r\n[Parsed_drawtext_12 @ 000001dcf3803d40] Using "C:/WINDOWS/fonts/mingliu.ttc"\r\n'

**Comment by ehendrix23** [comment]
Can you try with adding the parameter --font /Windows/Fonts/arial.ttf :

`.\tesla_dashcam.exe --quality HIGH --layout WIDESCREEN --encoding x265 --compression veryslow --no-notification --font /Windows/Fonts/arial.ttf '\WSE\ServerFolders\Pictures\DashCam\TeslaCam - Copy\2019-05-07_13-35-02'`

Thx.

**Comment by raushel** [comment]
Using --font /Windows/Fonts/arial.ttf seems to be working. No more ffmpeg timestamp errors.

Thanks!

**Comment by ehendrix23** [comment]
Excellent, next release that will be the default path. :-)

**Comment by Alin-Dumitrescu** [comment]
Hello,
I am getting the same error even with that param. I downloaded the latest version of the ffmpeg. I think the issue is that i am running it from the E drive.

If i do "C:\Temp>E:\TeslaCam\tesla_dashcam\tesla_dashcam.exe --ffmpeg E:\TeslaCam\ffmpeg\bin\ffmpeg.exe --font /Windows/Fonts/arial.ttf E:\TeslaCam\" it seems to work.

E:\TeslaCam\tesla_dashcam>tesla_dashcam.exe --ffmpeg E:\TeslaCam\ffmpeg\bin\ffmpeg.exe --font /Windows/Fonts/arial.ttf E:\TeslaCam\
Discovered 10 folders with 92 clips to process.
        Processing 11 clips in folder E:\TeslaCam\2019-05-25_09-43-07 (1/10)
                Processing clip 1/11 from 05/25/19 09:32:49 and 59 seconds long.
                        Error trying to create clip for E:\TeslaCam\2019-05-25_09-43-07\2019-05-25_09-33-49. RC: 255
                        Command: ['E:\\TeslaCam\\ffmpeg\\bin\\ffmpeg.exe', '-i', 'E:\\TeslaCam\\2019-05-25_09-43-07\\2019-05-25_09-33-49-left_repeater.mp4', '-i', 'E:\\TeslaCam\\2019-05-25_09-43-07\\2019-05-25_09-33-49-front.mp4', '-i', 'E:\\TeslaCam\\2019-05-25_09-43-07\\2019-05-25_09-33-49-right_repeater.mp4', '-filter_complex', "color=duration=59.72:s=1280x960:c=black [base];[0:v] setpts=PTS-STARTPTS, scale=640x480 , hflip [left];[1:v] setpts=PTS-STARTPTS, scale=640x480  [front];[2:v] setpts=PTS-STARTPTS, scale=640x480 , hflip [right];[base][left] overlay=eof_action=pass:repeatlast=0:x=0:y=480 [left1];[left1][front] overlay=eof_action=pass:repeatlast=0:x=320:y=0 [front1];[front1][right] overlay=eof_action=pass:repeatlast=0:x=640:y=480[tmp0];[tmp0] drawtext=fontfile=/Windows/Fonts/arial.ttf:fontcolor=white:fontsize=16:borderw=2:bordercolor=black@1.0:x=(w/2-text_w/2):y=(h-(text_h*2)):text='%{pts\\:localtime\\:1558801969\\:%x %X}'", '-preset', 'medium', '-crf', '28', '-c:v', 'libx264', '-y', 'E:\\TeslaCam\\2019-05-25_09-33-49.mp4']
                        Error: b'ffmpeg version N-93913-g1a74b04737 Copyright (c) 2000-2019 the FFmpeg developers\r\n  built with gcc 8.3.1 (GCC) 20190414\r\n  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt\r\n  libavutil      56. 28.100 / 56. 28.100\r\n  libavcodec     58. 52.102 / 58. 52.102\r\n  libavformat    58. 27.103 / 58. 27.103\r\n  libavdevice    58.  7.100 / 58.  7.100\r\n  libavfilter     7. 54.101 /  7. 54.101\r\n  libswscale      5.  4.101 /  5.  4.101\r\n  libswresample   3.  4.100 /  3.  4.100\r\n  libpostproc    55.  4.100 / 55.  4.100\r\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from \'E:\\TeslaCam\\2019-05-25_09-43-07\\2019-05-25_09-33-49-left_repeater.mp4\':\r\n  Metadata:\r\n    major_brand     : mp42\r\n    minor_version   : 0\r\n    compatible_brands: mp42mp41isomiso2\r\n    creation_time   : 2019-05-25T16:32:49.000000Z\r\n  Duration: 00:00:59.72, start: 0.000000, bitrate: 4004 kb/s\r\n    Stream #0:0(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1280x960, 4000 kb/s, SAR 1:1 DAR 4:3, 36 fps, 36 tbr, 10k tbn, 20k tbc (default)\r\n    Metadata:\r\n      creation_time   : 2019-05-25T16:32:49.000000Z\r\n      handler_name    : VideoHandler\r\nInput #1, mov,mp4,m4a,3gp,3g2,mj2, from \'E:\\TeslaCam\\2019-05-25_09-43-07\\2019-05-25_09-33-49-front.mp4\':\r\n  Metadata:\r\n    major_brand     : mp42\r\n    minor_version   : 0\r\n    compatible_brands: mp42mp41isomiso2\r\n    creation_time   : 2019-05-25T16:32:49.000000Z\r\n  Duration: 00:00:59.72, start: 0.000000, bitrate: 4004 kb/s\r\n    Stream #1:0(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1280x960, 4001 kb/s, SAR 1:1 DAR 4:3, 36 fps, 36 tbr, 10k tbn, 20k tbc (default)\r\n    Metadata:\r\n      creation_time   : 2019-05-25T16:32:49.000000Z\r\n      handler_name    : VideoHandler\r\nInput #2, mov,mp4,m4a,3gp,3g2,mj2, from \'E:\\TeslaCam\\2019-05-25_09-43-07\\2019-05-25_09-33-49-right_repeater.mp4\':\r\n  Metadata:\r\n    major_brand     : mp42\r\n    minor_version   : 0\r\n    compatible_brands: mp42mp41isomiso2\r\n    creation_time   : 2019-05-25T16:32:49.000000Z\r\n  Duration: 00:00:59.69, start: 0.000000, bitrate: 4005 kb/s\r\n    Stream #2:0(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1280x960, 4001 kb/s, SAR 1:1 DAR 4:3, 36 fps, 36 tbr, 10k tbn, 20k tbc (default)\r\n    Metadata:\r\n      creation_time   : 2019-05-25T16:32:49.000000Z\r\n      handler_name    : VideoHandler\r\nFontconfig error: Cannot load default config file\r\n[Parsed_drawtext_12 @ 000001a55323c040] Using "C:/WINDOWS/fonts/mingliu.ttc"\r\n'

**Comment by ehendrix23** [comment]
FYI,

Just released test version that includes a fix for this:
https://github.com/ehendrix23/tesla_dashcam/releases/tag/v0.1.10b0

**Comment by raushel** [comment]
Had to add --font /Windows/Fonts/arial.ttf for v0.1.10 via pip and Server 2019
