### ISSUE TITLE
Merge failed 1.9

### ISSUE THREAD

**Issue by jaimevisser** [ehendrix23/tesla_dashcam#30]
Merging fails for some events:
`Error trying to create movie ./2019-05-24_17-16-20.mp4. RC: 1
		Command: ['/var/folders/cr/j5xnfds52f30kv_7bl1gzhsh0000gn/T/_MEIhEhD2I/ffmpeg', '-i', './2019-05-24_17-07-15.mp4', '-i', './2019-05-24_17-08-15.mp4', '-i', './2019-05-24_17-09-15.mp4', '-i', './2019-05-24_17-10-15.mp4', '-i', './2019-05-24_17-11-16.mp4', '-i', './2019-05-24_17-12-16.mp4', '-i', './2019-05-24_17-13-16.mp4', '-i', './2019-05-24_17-14-16.mp4', '-i', './2019-05-24_17-15-17.mp4', '-i', './2019-05-24_17-16-17.mp4', '-i', './2019-05-24_17-16-20.mp4', '-filter_complex', '[0:v:0] [1:v:0] [2:v:0] [3:v:0] [4:v:0] [5:v:0] [6:v:0] [7:v:0] [8:v:0] [9:v:0] [10:v:0] concat=n=11:v=1:a=0 [v]', '-map', '[v]', '-preset', 'medium', '-crf', '28', '-b:v', '2500K', '-c:v', 'h264_videotoolbox', '-y', './2019-05-24_17-16-20.mp4']
		Error: b"ffmpeg version N-93225-g37e4c226c0-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers\n  built with Apple LLVM version 10.0.0 (clang-1000.11.45.5)\n  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay\n  libavutil      56. 26.100 / 56. 26.100\n  libavcodec     58. 47.102 / 58. 47.102\n  libavformat    58. 26.101 / 58. 26.101\n  libavdevice    58.  6.101 / 58.  6.101\n  libavfilter     7. 48.100 /  7. 48.100\n  libswscale      5.  4.100 /  5.  4.100\n  libswresample   3.  4.100 /  3.  4.100\n  libpostproc    55.  4.100 / 55.  4.100\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from './2019-05-24_17-07-15.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.26.101\n  Duration: 00:00:59.84, start: 0.000000, bitrate: 2527 kb/s\n    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x960 [SAR 1:1 DAR 4:3], 2526 kb/s, 25 fps, 25 tbr, 12800 tbn, 25600 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\nInput #1, mov,mp4,m4a,3gp,3g2,mj2, from './2019-05-24_17-08-15.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.26.101\n  Duration: 00:00:59.80, start: 0.000000, bitrate: 2532 kb/s\n    Stream #1:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x960 [SAR 1:1 DAR 4:3], 2531 kb/s, 25 fps, 25 tbr, 12800 tbn, 25600 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\nInput #2, mov,mp4,m4a,3gp,3g2,mj2, from './2019-05-24_17-09-15.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.26.101\n  Duration: 00:00:59.80, start: 0.000000, bitrate: 2520 kb/s\n    Stream #2:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x960 [SAR 1:1 DAR 4:3], 2519 kb/s, 25 fps, 25 tbr, 12800 tbn, 25600 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\nInput #3, mov,mp4,m4a,3gp,3g2,mj2, from './2019-05-24_17-10-15.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.26.101\n  Duration: 00:00:59.80, start: 0.000000, bitrate: 2534 kb/s\n    Stream #3:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x960 [SAR 1:1 DAR 4:3], 2533 kb/s, 25 fps, 25 tbr, 12800 tbn, 25600 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\nInput #4, mov,mp4,m4a,3gp,3g2,mj2, from './2019-05-24_17-11-16.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.26.101\n  Duration: 00:00:59.80, start: 0.000000, bitrate: 2537 kb/s\n    Stream #4:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x960 [SAR 1:1 DAR 4:3], 2536 kb/s, 25 fps, 25 tbr, 12800 tbn, 25600 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\nInput #5, mov,mp4,m4a,3gp,3g2,mj2, from './2019-05-24_17-12-16.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.26.101\n  Duration: 00:00:59.80, start: 0.000000, bitrate: 2529 kb/s\n    Stream #5:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x960 [SAR 1:1 DAR 4:3], 2528 kb/s, 25 fps, 25 tbr, 12800 tbn, 25600 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\nInput #6, mov,mp4,m4a,3gp,3g2,mj2, from './2019-05-24_17-13-16.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.26.101\n  Duration: 00:00:59.84, start: 0.000000, bitrate: 2545 kb/s\n    Stream #6:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x960 [SAR 1:1 DAR 4:3], 2544 kb/s, 25 fps, 25 tbr, 12800 tbn, 25600 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\nInput #7, mov,mp4,m4a,3gp,3g2,mj2, from './2019-05-24_17-14-16.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.26.101\n  Duration: 00:00:59.84, start: 0.000000, bitrate: 2524 kb/s\n    Stream #7:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x960 [SAR 1:1 DAR 4:3], 2523 kb/s, 25 fps, 25 tbr, 12800 tbn, 25600 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\nInput #8, mov,mp4,m4a,3gp,3g2,mj2, from './2019-05-24_17-15-17.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.26.101\n  Duration: 00:00:59.80, start: 0.000000, bitrate: 2533 kb/s\n    Stream #8:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x960 [SAR 1:1 DAR 4:3], 2532 kb/s, 25 fps, 25 tbr, 12800 tbn, 25600 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\nInput #9, mov,mp4,m4a,3gp,3g2,mj2, from './2019-05-24_17-16-17.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.26.101\n  Duration: 00:00:59.84, start: 0.000000, bitrate: 2526 kb/s\n    Stream #9:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x960 [SAR 1:1 DAR 4:3], 2525 kb/s, 25 fps, 25 tbr, 12800 tbn, 25600 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\nInput #10, mov,mp4,m4a,3gp,3g2,mj2, from './2019-05-24_17-16-20.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.26.101\n  Duration: 00:00:02.80, start: 0.000000, bitrate: 2637 kb/s\n    Stream #10:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x960 [SAR 1:1 DAR 4:3], 2634 kb/s, 25 fps, 25 tbr, 12800 tbn, 25600 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\nCodec AVOption preset (Configuration preset) specified for output file #0 (./2019-05-24_17-16-20.mp4) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.\nCodec AVOption crf (Select the quality for constant quality mode) specified for output file #0 (./2019-05-24_17-16-20.mp4) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.\nOutput ./2019-05-24_17-16-20.mp4 same as Input #10 - exiting\nFFmpeg cannot edit existing files in-place.\n"`

I can send the failing files if that would help.

**Comment by ehendrix23** [comment]
if you can provide the exact command you used and the complete output on the screen that would already be helpful.

**Comment by jaimevisser** [comment]
Just ran `tesla_dashcam` with defaults/no options in my savedclips folder (which I had first copied to my macbook's drive).

**Comment by ehendrix23** [comment]
Can you provide the output, not just from the error but everything before it where it states the folder and files it is doing etc..

Thx.

**Comment by ehendrix23** [comment]
FYI,

Just released test version that includes a fix for this:
https://github.com/ehendrix23/tesla_dashcam/releases/tag/v0.1.10b0

**Comment by jaimevisser** [comment]
Will test right away.

**Comment by jaimevisser** [comment]
That fixed one of the two folders that were not merging. Also behaviour with default options seems to have changed: resulting files are no longer placed next to the event folders.

Output:
`GPU acceleration is enabled
Discovered 2 folders with 12 clips to process.
	Processing 2 clips in folder ./2019-05-23_19-41-17 (1/2)
		Processing clip 1/2 from 05/23/19 19:39:52 and 59 seconds long.
			Error trying to create clip for ./2019-05-23_19-41-17/2019-05-23_19-40-53. RC: 1
			Command: ['/var/folders/cr/j5xnfds52f30kv_7bl1gzhsh0000gn/T/_MEIcYpkhy/ffmpeg', '-i', './2019-05-23_19-41-17/2019-05-23_19-40-53-front.mp4', '-filter_complex', "color=duration=59.8:s=1280x960:c=black [base];color=duration=59.8:s=0x480:c=black [left];[0:v] setpts=PTS-STARTPTS, scale=640x480  [front];color=duration=59.8:s=640x480:c=black [right];[base][left] overlay=eof_action=pass:repeatlast=0:x=0:y=480 [left1];[left1][front] overlay=eof_action=pass:repeatlast=0:x=320:y=0 [front1];[front1][right] overlay=eof_action=pass:repeatlast=0:x=640:y=480[tmp0];[tmp0] drawtext=fontfile=/Library/Fonts/Arial.ttf:fontcolor=white:fontsize=16.0:borderw=2:bordercolor=black@1.0:x=(w/2-text_w/2):y=(h-(text_h*2)):text='%{pts\\:localtime\\:1558633192\\:%x %X}'", '-preset', 'medium', '-crf', '28', '-allow_sw', '1', '-b:v', '5000K', '-c:v', 'h264_videotoolbox', '-y', '/Users/jaime/Movies/Tesla_Dashcam/2019-05-23_19-40-53.mp4']
			Error: b'ffmpeg version N-93225-g37e4c226c0-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers\n  built with Apple LLVM version 10.0.0 (clang-1000.11.45.5)\n  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay\n  libavutil      56. 26.100 / 56. 26.100\n  libavcodec     58. 47.102 / 58. 47.102\n  libavformat    58. 26.101 / 58. 26.101\n  libavdevice    58.  6.101 / 58.  6.101\n  libavfilter     7. 48.100 /  7. 48.100\n  libswscale      5.  4.100 /  5.  4.100\n  libswresample   3.  4.100 /  3.  4.100\n  libpostproc    55.  4.100 / 55.  4.100\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from \'./2019-05-23_19-41-17/2019-05-23_19-40-53-front.mp4\':\n  Metadata:\n    major_brand     : mp42\n    minor_version   : 0\n    compatible_brands: mp42mp41isomiso2\n    creation_time   : 2019-05-23T17:39:52.000000Z\n  Duration: 00:00:59.80, start: 0.000000, bitrate: 3937 kb/s\n    Stream #0:0(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1280x960, 3934 kb/s, SAR 1:1 DAR 4:3, 35.94 fps, 36 tbr, 10k tbn, 20k tbc (default)\n    Metadata:\n      creation_time   : 2019-05-23T17:39:52.000000Z\n      handler_name    : VideoHandler\n[color @ 0x7ff785c17e80] Unable to parse option value "0x480" as image size\n    Last message repeated 1 times\n[color @ 0x7ff785c17e80] Error setting option s to value 0x480.\n[Parsed_color_1 @ 0x7ff785c17d80] Error applying options to the filter.\n[AVFilterGraph @ 0x7ff785c17340] Error initializing filter \'color\' with args \'duration=59.8:s=0x480:c=black\'\nError initializing complex filters.\nInvalid argument\n'


		Processing clip 2/2 from 05/23/19 19:40:53 and 22 seconds long.
			Error trying to create clip for ./2019-05-23_19-41-17/2019-05-23_19-41-16. RC: 1
			Command: ['/var/folders/cr/j5xnfds52f30kv_7bl1gzhsh0000gn/T/_MEIcYpkhy/ffmpeg', '-i', './2019-05-23_19-41-17/2019-05-23_19-41-16-front.mp4', '-filter_complex', "color=duration=22.83:s=1280x960:c=black [base];color=duration=22.83:s=0x480:c=black [left];[0:v] setpts=PTS-STARTPTS, scale=640x480  [front];color=duration=22.83:s=640x480:c=black [right];[base][left] overlay=eof_action=pass:repeatlast=0:x=0:y=480 [left1];[left1][front] overlay=eof_action=pass:repeatlast=0:x=320:y=0 [front1];[front1][right] overlay=eof_action=pass:repeatlast=0:x=640:y=480[tmp0];[tmp0] drawtext=fontfile=/Library/Fonts/Arial.ttf:fontcolor=white:fontsize=16.0:borderw=2:bordercolor=black@1.0:x=(w/2-text_w/2):y=(h-(text_h*2)):text='%{pts\\:localtime\\:1558633253\\:%x %X}'", '-preset', 'medium', '-crf', '28', '-allow_sw', '1', '-b:v', '5000K', '-c:v', 'h264_videotoolbox', '-y', '/Users/jaime/Movies/Tesla_Dashcam/2019-05-23_19-41-16.mp4']
			Error: b'ffmpeg version N-93225-g37e4c226c0-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers\n  built with Apple LLVM version 10.0.0 (clang-1000.11.45.5)\n  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay\n  libavutil      56. 26.100 / 56. 26.100\n  libavcodec     58. 47.102 / 58. 47.102\n  libavformat    58. 26.101 / 58. 26.101\n  libavdevice    58.  6.101 / 58.  6.101\n  libavfilter     7. 48.100 /  7. 48.100\n  libswscale      5.  4.100 /  5.  4.100\n  libswresample   3.  4.100 /  3.  4.100\n  libpostproc    55.  4.100 / 55.  4.100\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from \'./2019-05-23_19-41-17/2019-05-23_19-41-16-front.mp4\':\n  Metadata:\n    major_brand     : mp42\n    minor_version   : 0\n    compatible_brands: mp42mp41isomiso2\n    creation_time   : 2019-05-23T17:40:53.000000Z\n  Duration: 00:00:22.83, start: 0.000000, bitrate: 3922 kb/s\n    Stream #0:0(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1280x960, 3919 kb/s, SAR 1:1 DAR 4:3, 35.92 fps, 36 tbr, 10k tbn, 20k tbc (default)\n    Metadata:\n      creation_time   : 2019-05-23T17:40:53.000000Z\n      handler_name    : VideoHandler\n[color @ 0x7f8975508600] Unable to parse option value "0x480" as image size\n    Last message repeated 1 times\n[color @ 0x7f8975508600] Error setting option s to value 0x480.\n[Parsed_color_1 @ 0x7f8975508540] Error applying options to the filter.\n[AVFilterGraph @ 0x7f8975500d00] Error initializing filter \'color\' with args \'duration=22.83:s=0x480:c=black\'\nError initializing complex filters.\nInvalid argument\n'


	Processing 10 clips in folder ./2019-05-24_14-32-34 (2/2)
		Processing clip 1/10 from 05/24/19 14:22:33 and 59 seconds long.
		Processing clip 2/10 from 05/24/19 14:23:33 and 59 seconds long.
		Processing clip 3/10 from 05/24/19 14:24:34 and 59 seconds long.
		Processing clip 4/10 from 05/24/19 14:25:35 and 59 seconds long.
		Processing clip 5/10 from 05/24/19 14:26:35 and 59 seconds long.
		Processing clip 6/10 from 05/24/19 14:27:36 and 59 seconds long.
		Processing clip 7/10 from 05/24/19 14:28:36 and 59 seconds long.
		Processing clip 8/10 from 05/24/19 14:29:36 and 59 seconds long.
		Processing clip 9/10 from 05/24/19 14:30:37 and 59 seconds long.
		Processing clip 10/10 from 05/24/19 14:31:37 and 53 seconds long.
		Creating movie /Users/jaime/Movies/Tesla_Dashcam/2019-05-24T14-22-33_2019-05-24T14-32-30.mp4, please be patient.
	Movie /Users/jaime/Movies/Tesla_Dashcam/2019-05-24T14-22-33_2019-05-24T14-32-30.mp4 for folder ./2019-05-24_14-32-34 is ready.
All folders have been processed, resulting movie files are located in /Users/jaime/Movies/Tesla_Dashcam
Total processing time: 0:03:03`
>

**Comment by ehendrix23** [comment]
Release v.0.1.10 has been made available with the fix:
https://github.com/ehendrix23/tesla_dashcam/releases/tag/v0.1.10

**Comment by jaimevisser** [comment]
Not quite perfect, but close!

It's now properly ignoring the 0kb files leaving the non-recorded repeater black in the final merge. Unfortunately the other repeater cam is not merged even though those clips are available and play just fine on their own.

**Comment by ehendrix23** [comment]
Could you provide me the output for that and also say which repeater cam has the issue (and clearly the other one not being merged either then). 
I'm assuming it is still doing the front, just not the repeater ones then correct?

I'm going on vacation but will then look at it when I'm back.

**Comment by jaimevisser** [comment]
Yeah, the front is merging just fine.

You can find the source files for the failing merge at https://we.tl/t-8fxRf2FXGw (wetransfer link) so you can test while developing.

**Comment by ehendrix23** [comment]
Apologies; vacation, summer time, .... not been able to spend a lot of time on this.

Just tried to download but clearly by now it has been expired. Do you still have the issue with 0.1.11 (assuming you do); if so can you re-provide the source files?

thx.

**Comment by jaimevisser** [comment]
Hmm, my 3 has been making significantly less 0kb files on latest update. Will try with .12 and latest batch of video's.

**Comment by ehendrix23** [comment]
Assuming no issues anymore. Please open a new issue if there are.
