### ISSUE TITLE
Add periodic monitor option for persistent storage

### ISSUE THREAD

**Issue by exime** [ehendrix23/tesla_dashcam#32]
For installations that use persistent storage of some sort (NAS, in my case), it would be helpful to have a --monitor-like option to periodically check for videos to merge - which would work in conjunction with --delete_source.

**Comment by ehendrix23** [comment]
As mentioned, was already thinking of this but won't be in next release. :-)

However, with the next release --delete_source will also work when not using --monitor. Hence then as a potential work-around you could schedule it to run every night with --delete_source. If there are any files it will then process and delete the source files. If no files it will just exit with an error. :-)

**Comment by LBegnaud** [comment]
note that if there were any corrupt files in the directory, they aren't deleted with the new version. This causes the folder deletion to fail:

```
Processing 11 clips in folder ..\TeslaCam\2019-05-27_17-52-30 (4/12)
                Processing clip 1/11 from 05/27/19 17:42:21 and 59 seconds long.
                Processing clip 2/11 from 05/27/19 17:43:22 and 59 seconds long.
                Processing clip 3/11 from 05/27/19 17:44:22 and 59 seconds long.
                Processing clip 4/11 from 05/27/19 17:45:22 and 59 seconds long.
                Processing clip 5/11 from 05/27/19 17:46:22 and 59 seconds long.
                Processing clip 6/11 from 05/27/19 17:47:23 and 59 seconds long.
                Processing clip 7/11 from 05/27/19 17:48:23 and 59 seconds long.
                Processing clip 8/11 from 05/27/19 17:49:23 and 59 seconds long.
                Processing clip 9/11 from 05/27/19 17:50:24 and 59 seconds long.
                Processing clip 10/11 from 05/27/19 17:51:24 and 59 seconds long.
                Processing clip 11/11 from 05/27/19 17:52:24 and 4 seconds long.
                Creating movie .\TeslaCam_Merged\2019-05-27T17-42-21_2019-05-27T17-52-28.mp4, please be patient.
                Deleting files and folder ..\TeslaCam\2019-05-27_17-52-30
                Error trying to remove folder ..\TeslaCam\2019-05-27_17-52-30: [WinError 145] The directory is not empty: '..\\TeslaCam\\2019-05-27_17-52-30'
        Movie .\TeslaCam_Merged\2019-05-27T17-42-21_2019-05-27T17-52-28.mp4 for folder ..\TeslaCam\2019-05-27_17-52-30 is ready.
```

**Comment by ehendrix23** [comment]
Added option to monitor for existence of a folder (or file) and if there is then to start processing files.
Doing this will ensure that we don't start processing before all the files are there. My issue was that could see a folder is there but files are still being added. How long do I wait? That depends then on how fast the transfer from the source to that other storage is. Doing it through this ensures we do not start scanning and processing until all folders/files to be processed are indeed there.

 If a file is provided then it will be removed upon completion of processing. Can thus be used as well to programmatically detect if processing was completed. :-)
