### ISSUE TITLE
Release v0.1.10 DMG contains beta

### ISSUE THREAD

**Issue by aseniah** [ehendrix23/tesla_dashcam#37]
The DMG file for Release v0.1.10 contains the v0.1.10b0 beta version.

**Comment by jdandrea** [comment]
I'm seeing this when I run the file in this DMG:

```
New release v0.1.10 is available for download (https://github.com/ehendrix23/tesla_dashcam/releases/tag/v0.1.10). You are currently on v0.1.10b0. Use --check-for-update to get latest release notes.
GPU acceleration is enabled
Traceback (most recent call last):
  File "tesla_dashcam/tesla_dashcam.py", line 2251, in <module>
  File "tesla_dashcam/tesla_dashcam.py", line 2109, in main
FileNotFoundError: [Errno 2] No such file or directory: ''
[38094] Failed to execute script tesla_dashcam
```

**Comment by richpreuss** [comment]
This is still an issue. Has v0.1.10 DMG been released? This is what I see:

> RICHARDS-MBP:~ rpreuss$ /Applications/tesla_dashcam --rear --output ~/documents/Tesla/Movies --monitor_once --delete_source SavedClips
> New release v0.1.10 is available for download (https://github.com/ehendrix23/tesla_dashcam/releases/tag/v0.1.10). You are currently on v0.1.10b0. Use --check-for-update to get latest release notes.
> GPU acceleration is enabled
> Monitoring for TeslaCam Drive to be inserted. Press CTRL-C to stop
> ^CMonitoring stopped due to CTRL-C.
> Traceback (most recent call last):
>   File "tesla_dashcam/tesla_dashcam.py", line 2181, in main

**Comment by zzpaulzz** [comment]
Same here.  Downloaded yesterday.

**Comment by dhassman** [comment]
Same here - downloaded (again) today.

**Comment by jerrycallahan66** [comment]
Me too.

**Comment by ehendrix23** [comment]
Just pushed release 0.1.11, this time making sure version information within it is 0.1.11 :-)
