### ISSUE TITLE
Unable to delete source files when directory is not empty

### ISSUE THREAD

**Issue by pinguozzo** [ehendrix23/tesla_dashcam#40]
Hi, 
Just using the latest version available.

While running the following command: 
./tesla_dashcam /Volumes/NO\ NAME/TeslaCam/SavedClips/ --output /Users/user/Movies/TeslaCam/SavedClips/ --merge --delete-source

I get this output:
Creating movie /Users/user/Movies/TeslaCam/SavedClips/2019-05-31T19-02-46_2019-05-31T19-12-46.mp4, please be patient.
		Deleting files and folder /Volumes/NO NAME/TeslaCam/SavedClips/2019-05-31_19-12-51
		Error trying to remove folder /Volumes/NO NAME/TeslaCam/SavedClips/2019-05-31_19-12-51: [Errno 66] Directory not empty: '/Volumes/NO NAME/TeslaCam/SavedClips/2019-05-31_19-12-51'

P.S.
I've downloaded and installed the latest version attached here: 
https://github.com/ehendrix23/tesla_dashcam/releases/download/v0.1.10/tesla_dashcam.dmg

but: 
./tesla_dashcam --version
tesla_dashcam v0.1.10b0

Thanks for your great work!

**Comment by ehendrix23** [comment]
Not 100% sure but have a working theory on this. When we scan for the relevant files to create the video we do not include any for which the video file is corrupt. But then when deleting we only delete the clips we processed, and thus not the ones that were corrupt.
This then results in files left and hence unable to remove the folder.

Can you check for when this happens if there are indeed files left in the source folder and that those files are like 0 bytes (or extremely small like just 200 bytes or so).
That would then at least confirm my suspicion on this one. :-)

**Comment by LBegnaud** [comment]
that is absolutely what is happening here. Happens to me, too.

**Comment by chriztrax25** [comment]
same here but only for certain directories with 0 byte files

```
Error trying to remove folder /Volumes/TESLACAM/TeslaCam/SavedClips/2019-06-03_19-37-40: [Errno 66] Directory not empty: '/Volumes/TESLACAM/TeslaCam/SavedClips/2019-06-03_19-37-40'
```

0 byte files

```
$ cd  /Volumes/TESLACAM/TeslaCam/SavedClips/2019-06-03_19-37-40
$ ls -l
total 227776
-rwxrwxrwx  1 self  staff         0 Jun  3 19:31 2019-06-03_19-32-34-left_repeater.mp4
-rwxrwxrwx  1 self  staff  24477690 Jun  3 19:32 2019-06-03_19-32-34-right_repeater.mp4
-rwxrwxrwx  1 self  staff         0 Jun  3 19:32 2019-06-03_19-33-34-left_repeater.mp4
-rwxrwxrwx  1 self  staff  22259271 Jun  3 19:33 2019-06-03_19-33-34-right_repeater.mp4
-rwxrwxrwx  1 self  staff         0 Jun  3 19:33 2019-06-03_19-34-34-left_repeater.mp4
-rwxrwxrwx  1 self  staff  20894830 Jun  3 19:34 2019-06-03_19-34-34-right_repeater.mp4
-rwxrwxrwx  1 self  staff         0 Jun  3 19:35 2019-06-03_19-36-35-left_repeater.mp4
-rwxrwxrwx  1 self  staff  22599580 Jun  3 19:36 2019-06-03_19-36-35-right_repeater.mp4
-rwxrwxrwx  1 self  staff         0 Jun  3 19:36 2019-06-03_19-37-35-left_repeater.mp4
-rwxrwxrwx  1 self  staff  24882289 Jun  3 19:37 2019-06-03_19-37-35-right_repeater.mp4
-rwxrwxrwx  1 self  staff         0 Jun  3 19:37 2019-06-03_19-37-38-left_repeater.mp4
-rwxrwxrwx  1 self  staff   1410986 Jun  3 19:37 2019-06-03_19-37-38-right_repeater.mp4
```

**Comment by chriztrax** [comment]
same here but only for certain directories with 0 byte files
```
Error trying to remove folder /Volumes/TESLACAM/TeslaCam/SavedClips/2019-06-03_19-37-40: [Errno 66] Directory not empty: '/Volumes/TESLACAM/TeslaCam/SavedClips/2019-06-03_19-37-40'
0 byte files
```
```
$ cd  /Volumes/TESLACAM/TeslaCam/SavedClips/2019-06-03_19-37-40
$ ls -l
total 227776
-rwxrwxrwx  1 self  staff         0 Jun  3 19:31 2019-06-03_19-32-34-left_repeater.mp4
-rwxrwxrwx  1 self  staff  24477690 Jun  3 19:32 2019-06-03_19-32-34-right_repeater.mp4
-rwxrwxrwx  1 self  staff         0 Jun  3 19:32 2019-06-03_19-33-34-left_repeater.mp4
-rwxrwxrwx  1 self  staff  22259271 Jun  3 19:33 2019-06-03_19-33-34-right_repeater.mp4
-rwxrwxrwx  1 self  staff         0 Jun  3 19:33 2019-06-03_19-34-34-left_repeater.mp4
-rwxrwxrwx  1 self  staff  20894830 Jun  3 19:34 2019-06-03_19-34-34-right_repeater.mp4
-rwxrwxrwx  1 self  staff         0 Jun  3 19:35 2019-06-03_19-36-35-left_repeater.mp4
-rwxrwxrwx  1 self  staff  22599580 Jun  3 19:36 2019-06-03_19-36-35-right_repeater.mp4
-rwxrwxrwx  1 self  staff         0 Jun  3 19:36 2019-06-03_19-37-35-left_repeater.mp4
-rwxrwxrwx  1 self  staff  24882289 Jun  3 19:37 2019-06-03_19-37-35-right_repeater.mp4
-rwxrwxrwx  1 self  staff         0 Jun  3 19:37 2019-06-03_19-37-38-left_repeater.mp4
-rwxrwxrwx  1 self  staff   1410986 Jun  3 19:37 2019-06-03_19-37-38-right_repeater.mp4
```
