### ISSUE TITLE
ImportError: cannot import name 'run'

### ISSUE THREAD

**Issue by pimvdnoll** [ehendrix23/tesla_dashcam#42]
This library is amazing. Want to get it up and running on my NAS too so I can automate the merges and further processing for uploads to a cloud.

When installed tesla-dashcam through pip (was successful) I can't run the python file:

DiskStation> python3 tesla_dashcam.py --output /volume1/NetBackup/2019-06-11_19-47-57.mp4 /volume1/NetBackup/2019-06-11_19-47-57
Traceback (most recent call last):
  File "tesla_dashcam.py", line 13, in <module>
    from subprocess import CalledProcessError, run
ImportError: cannot import name 'run'
DiskStation>

can you help me please?

**Comment by remimarenco** [comment]
Hi @pimvdnoll,

By looking at [subprocess documentation](https://docs.python.org/3/library/subprocess.html#using-the-subprocess-module), it seems like `run` has been added in Python 3.5.

Could you double check your Python version? (`python -V`)
In the [requirements](https://docs.python.org/3/library/subprocess.html#using-the-subprocess-module), we seem to need 3.7.

**Comment by pimvdnoll** [comment]
ah, I run 3.5. I'll have a look if I can upgrade this on the Synology NAS. Thnx!
