### ISSUE TITLE
Mirror display

### ISSUE THREAD

**Issue by bahree** [ehendrix23/tesla_dashcam#45]
Hi, I am curious - is there an option for a mirror display that can show both repeater cams stacked next to each other - similar to how NateMccomb has done [here](https://github.com/NateMccomb/TeslaCamViewer). You can see a [video uploaded here](https://youtu.be/dri6_cSDTkA?t=318) (starting at 5:18). Is this possible?

https://www.youtube.com/watch?v=dri6_cSDTkA&feature=youtu.be

**Comment by ehendrix23** [comment]
So front camera is on top, rear facing cameras are next to each other below the front camera? Yeah, that is actually the default called FULLSCREEN layout. 
For each layout you can have the rear cameras being mirrored or not. Mirrored is default and using --rear you can see rear.

**Comment by ehendrix23** [comment]
Closing
