### ISSUE TITLE
Windows output file failures

### ISSUE THREAD

**Issue by emorog** [ehendrix23/tesla_dashcam#48]
running latest Release v0.1.10, (although it claims there is a newer version and says i'm running v0.1.10b0)

I am running it against a folder, as i have done in the past.  But now it is writing the output to an empty file name as : [user]\\Videos\\Tesla_Dashcam\\.mp4

Output:
E:\tesla_dashcam>tesla_dashcam.exe --no-check_for_update ..\TeslaCam\SavedClips\2019-06-01_23-42-08
Discovered 1 folders with 10 clips to process.
        Processing 10 clips in folder ..\TeslaCam\SavedClips\2019-06-01_23-42-08 (1/1)
                Processing clip 1/10 from 06/01/19 23:31:56 and 59 seconds long.
                Processing clip 2/10 from 06/01/19 23:32:56 and 59 seconds long.
                Processing clip 3/10 from 06/01/19 23:33:57 and 59 seconds long.
                Processing clip 4/10 from 06/01/19 23:34:57 and 59 seconds long.
                Processing clip 5/10 from 06/01/19 23:35:57 and 59 seconds long.
                Processing clip 6/10 from 06/01/19 23:36:57 and 59 seconds long.
                Processing clip 7/10 from 06/01/19 23:37:58 and 59 seconds long.
                Processing clip 8/10 from 06/01/19 23:38:58 and 59 seconds long.
                Processing clip 9/10 from 06/01/19 23:39:58 and 59 seconds long.
                Processing clip 10/10 from 06/01/19 23:40:58 and 53 seconds long.
                Creating movie C:\Users\user\Videos\Tesla_Dashcam\2019-06-01T23-31-56_2019-06-01T23-41-51.mp4, please be patient.
        Movie C:\Users\user\Videos\Tesla_Dashcam\2019-06-01T23-31-56_2019-06-01T23-41-51.mp4 for folder ..\TeslaCam\SavedClips\2019-06-01_23-42-08 is ready.
        Creating movie C:\Users\user\Videos\Tesla_Dashcam\.mp4, please be patient.
Movie **C:\Users\user\Videos\Tesla_Dashcam\\.mp4** has been created, enjoy.
Total processing time: 0:03:02

**Comment by smeehrrr** [comment]
Also seeing this issue, is there any workaround?

**Comment by smeehrrr** [comment]
If you're comfortable installing Python, it looks like the bug is fixed in the source release here: https://github.com/ehendrix23/tesla_dashcam/releases/tag/v0.1.11

**Comment by ehendrix23** [comment]
Apologies, summer resulting in more time outside, vacation, business travel. I was just going to say that v0.1.11 should have a fix for this.
Working right now on getting it pushed out.

**Comment by ehendrix23** [comment]
v0.1.11 has been released that should have the fix for this.
