### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by itsrainingben** [ehendrix23/tesla_dashcam#49]
Appreciate this script! Is it possible to: 

- Set tesla_dashcam to monitor a specific directory (just on a screen or tmux'd terminal session) for eg; ~/Movies/Tesla_Dashcam/
- Then, process folders as they appear in that directory then..
- Name them after their dated folder convention.

I'm using teslapi/USB so dashcam/sentry footage automatically gets transferred to the directory above. I'm manually processing each as they come in for review and I noticed you have a --monitor flag but cannot specify the monitored location beyond a plugged in USB drive.

Again, appreciate this script!

**Comment by ehendrix23** [comment]
This is on my to-do list. :-)

**Comment by itsrainingben** [comment]
Thought it might be, thanks for your work. Very much appreciated!
