### ISSUE TITLE
Rendering lost red color and brightness

### ISSUE THREAD

**Issue by jerrycallahan66** [ehendrix23/tesla_dashcam#50]
All my resulting files have lost the red tint. Red shows as orange.

Also the front video is very dim. The left mirror is good. The right mirror is mid-way brightness.

The left mirror captures or renderings are often black, i.e., no picture.

Are there an adjustment options to fix these issues?

**Comment by supercazzola** [comment]
I have the same issue with the left mirror renderings being black too
-----

The problem with the world is that the intelligent people are full of doubts, while the stupid ones are full of confidence.

**Comment by ehendrix23** [comment]
Check the  --quality option. Default is LOWER as during my testing it came back still with good quality yet fast rendering times.

Further, also always good to compare with original clips as issue might not be merging of video but rather what was recorded instead.

**Comment by ehendrix23** [comment]
Closing. If issue persist please open new issue providing answer and referencing this issue.

Thank you.
