### ISSUE TITLE
ffmpeg errors after 0.1.11, server 2019 timestamps

### ISSUE THREAD

**Issue by raushel** [ehendrix23/tesla_dashcam#51]
Started getting ffmpeg errors after v 0.1.11 was released. Thought it was associated with 2019.24.4, but looking at logs broke starting on the 29th after 0.1.11 was released. Somehow still having problems with 0.1.10, but not sure how.

Error from compiled binary on Server 2019, but also getting ffmpeg errors with pip / latest download of ffmpeg. Binary seems to work fine on Windows 10 1903.

.\tesla_dashcam.exe .\TeslaCam\2019-08-03_19-00-19\

Error trying to create clip for .\TeslaCam\2019-08-03_19-00-19\2019-08-03_18-59-15. RC: 3221226356
                        Command: ['C:\\Users\\SVCTES~1\\AppData\\Local\\Temp\\_MEI33882\\ffmpeg.exe', '-i', '.\\TeslaCam\\2019-08-03_19-00-19\\2019-08-03_18-59-15-left_repeater.mp4', '-i', '.\\TeslaCam\\2019-08-03_19-00-19\\2019-08-03_18-59-15-front.mp4', '-i', '.\\TeslaCam\\2019-08-03_19-00-19\\2019-08-03_18-59-15-right_repeater.mp4', '-filter_complex', "color=duration=56.69:s=1280x960:c=black [base];[0:v] setpts=PTS-STARTPTS, scale=640x480 , hflip [left];[1:v] setpts=PTS-STARTPTS, scale=640x480  [front];[2:v] setpts=PTS-STARTPTS, scale=640x480 , hflip [right];[base][left] overlay=eof_action=pass:repeatlast=0:x=0:y=480 [left1];[left1][front] overlay=eof_action=pass:repeatlast=0:x=320:y=0 [front1];[front1][right] overlay=eof_action=pass:repeatlast=0:x=640:y=480[tmp0];[tmp0] drawtext=fontfile=/Windows/Fonts/arial.ttf:fontcolor=white:fontsize=16.0:borderw=2:bordercolor=black@1.0:x=(w/2-text_w/2):y=(h-(text_h*2)):text='%{pts\\:localtime\\:1564876756\\:%x %X}'", '-preset', 'medium', '-crf', '28', '-c:v', 'libx264', '-y', 'C:\\Users\\svctesla\\Videos\\Tesla_Dashcam\\2019-08-03_18-59-15.mp4']
                        Error: b'ffmpeg version 4.1.1 Copyright (c) 2000-2019 the FFmpeg developers\r\n  built with gcc 8.2.1 (GCC) 20190212\r\n  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth\r\n  libavutil      56. 22.100 / 56. 22.100\r\n  libavcodec     58. 35.100 / 58. 35.100\r\n  libavformat    58. 20.100 / 58. 20.100\r\n  libavdevice    58.  5.100 / 58.  5.100\r\n  libavfilter     7. 40.101 /  7. 40.101\r\n  libswscale      5.  3.100 /  5.  3.100\r\n  libswresample   3.  3.100 /  3.  3.100\r\n  libpostproc    55.  3.100 / 55.  3.100\r\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from \'.\\TeslaCam\\2019-08-03_19-00-19\\2019-08-03_18-59-15-left_repeater.mp4\':\r\n  Metadata:\r\n    major_brand     : mp42\r\n    minor_version   : 0\r\n    compatible_brands: mp42mp41isomiso2\r\n    creation_time   : 2019-08-03T23:59:17.000000Z\r\n  Duration: 00:00:55.91, start: 0.000000, bitrate: 4011 kb/s\r\n    Stream #0:0(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1280x960, 4005 kb/s, SAR 1:1 DAR 4:3, 36.02 fps, 36 tbr, 10k tbn, 20k tbc (default)\r\n    Metadata:\r\n      creation_time   : 2019-08-03T23:59:17.000000Z\r\n      handler_name    : VideoHandler\r\nInput #1, mov,mp4,m4a,3gp,3g2,mj2, from \'.\\TeslaCam\\2019-08-03_19-00-19\\2019-08-03_18-59-15-front.mp4\':\r\n  Metadata:\r\n    major_brand     : mp42\r\n    minor_version   : 0\r\n    compatible_brands: mp42mp41isomiso2\r\n    creation_time   : 2019-08-03T23:59:16.000000Z\r\n  Duration: 00:00:56.69, start: 0.000000, bitrate: 4005 kb/s\r\n    Stream #1:0(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1280x960, 3999 kb/s, SAR 1:1 DAR 4:3, 36.02 fps, 36 tbr, 10k tbn, 20k tbc (default)\r\n    Metadata:\r\n      creation_time   : 2019-08-03T23:59:16.000000Z\r\n      handler_name    : VideoHandler\r\nInput #2, mov,mp4,m4a,3gp,3g2,mj2, from \'.\\TeslaCam\\2019-08-03_19-00-19\\2019-08-03_18-59-15-right_repeater.mp4\':\r\n  Metadata:\r\n    major_brand     : mp42\r\n    minor_version   : 0\r\n    compatible_brands: mp42mp41isomiso2\r\n    creation_time   : 2019-08-03T23:59:17.000000Z\r\n  Duration: 00:00:56.33, start: 0.000000, bitrate: 3977 kb/s\r\n    Stream #2:0(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1280x960, 3971 kb/s, SAR 1:1 DAR 4:3, 36.02 fps, 36 tbr, 10k tbn, 20k tbc (default)\r\n    Metadata:\r\n      creation_time   : 2019-08-03T23:59:17.000000Z\r\n      handler_name    : VideoHandler\r\nFontconfig error: Cannot load default config file\r\n[Parsed_drawtext_12 @ 0000018a0e85da40] Using "C:/WINDOWS/fonts/mingliu.ttc"\r\n'

**Comment by raushel** [comment]
Not sure why 0.1.10 is throwing the same error when reverting pip back. 

--font \Windows\Fonts\Arial.ttf isn't working either.
--no-timestamps is the only way ffmpeg will run without errors now

**Comment by ehendrix23** [comment]
Can you check if you have Arial.ttf in your Windows\Fonts folder?

**Comment by raushel** [comment]
Yes, it's there: 
![image](https://user-images.githubusercontent.com/49056263/62644948-ebe85d00-b910-11e9-9d40-89b397a5e504.png)

**Comment by ehendrix23** [comment]
Right now still no solution. Based on everything I have found etc the way I specify the path right now should work.
Were any hotfixes or so installed on that server? Asking as you mentioned it also stopped working with 0.1.10 which was working before.

Further, can you try:
--font \Windows\Fonts\arial.ttf

On Windows there should not be a case-sensitivity but just in case for some reason there is within ffmpeg itself or so.

**Comment by raushel** [comment]
Looks like it's an issue of Powershell running against a network share (or having my CD as UNC while running the exe directly) vs using a hardlink to the same path. Something about the UNC path is breaking it. When I was troubleshooting the folder issue caused by 0.1.11 I was using the UNC path, creating the timestamp issue.

This is pretty unique to my situation as all of my scripts and sentry videos are stored on a file share on one VM, but being run by a scheduled task on different VM with Python installed:

![image](https://user-images.githubusercontent.com/49056263/62968513-d2dc2200-bdd0-11e9-8c93-d1f194f575ae.png)

Fails:
PS C:\WINDOWS\system32> \\WSE\ServerFolders\Pictures\DashCam\StitchTeslaCam.ps1

Success:
PS C:\serverfolders\pictures\DashCam> .\StitchTeslaCam.ps1

Not sure there's anything to do, but document the quirk.

**Comment by ehendrix23** [comment]
So you have everything (scripts, tesla_dashcam, videos) stored on server A. Then server B has Python installed and from there you run tesla_dashcam?

So assuming that in your PowerShell you then call tesla_dashcam as \WSE\ServerFolders\....\tesla_dashcam.py ?

**Comment by raushel** [comment]
cd is set to \\wse\ServerFolders\...\Dashcam\ and StichTeslaCam.ps1 is called from there, which will call pip tesla_dashcam via PATH (C:\Python37\Scripts on Python server)

![image](https://user-images.githubusercontent.com/49056263/63062823-d00c2a80-bebf-11e9-819a-0b39b11eefee.png)

If I hardlink to the UNC path, ffmpeg doesn't throw the font errors, wondering if since you can't cd to UNC paths in a standard cmd window if that is somehow causing related issues with ffmpeg, just not sure why.
