### ISSUE TITLE
Exception in thread Thread-2

### ISSUE THREAD

**Issue by nschubach** [ehendrix23/tesla_dashcam#54]
I get this thread exception in Windows (using gitbash, but it happens in CMD as well).  It seemed to start working once (because I just clicked it to run it, not thinking about command line) then afterwards:

 MINGW64 ~/Downloads/tesla_dashcam
$ ./tesla_dashcam.exe --output /d/tesla/ --layout WIDESCREEN
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "site-packages\win10toast\__init__.py", line 83, in _show_toast
AttributeError: 'ToastNotifier' object has no attribute 'classAtom'

Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "site-packages\win10toast\__init__.py", line 83, in _show_toast
AttributeError: 'ToastNotifier' object has no attribute 'classAtom'

Monitoring for TeslaCam Drive to be inserted. Press CTRL-C to stop
TeslaCam folder found on F:\.
Discovered 0 folders with 0 clips to process.
No clips found.
Total processing time: 0:00:00

Exiting monitoring as asked process once.

Now... I don't have Windows 10 (Win7), and didn't see an option to not use the "toast" notifier.  Maybe I missed it?

**Comment by nschubach** [comment]
If I specify a folder instead of letting it search, it doesn't fail.

(The notification thing would find the folder properly and tell me)

**Comment by ehendrix23** [comment]
Any way you can grab the latest version from the dev branch and run as python script? Been unable to reproduce on mine (but I have Windows 10). 

If not then hoping this is the fix. :-)

The option --no-notification disables those notifications.
