### ISSUE TITLE
error on Mac after upgrade from 0.1.9 > 0.1.12

### ISSUE THREAD

**Issue by cjolly3053** [ehendrix23/tesla_dashcam#58]
0.1.9 was working fine on my Mac but then I updated to 0.1.12 and getting this error:

Processing clip 3/38 from 08/21/19 08:00:34 and 58 seconds long.
			Error trying to create clip for /Users/cjolly3053/Desktop/RecentClips/2019-08-21_08-00-33. RC: 1
			Command: ['/var/folders/5p/rsq2zb8x2v373nbgw7rx3smm0000gn/T/_MEIeLLxz7/ffmpeg', '-i', '/Users/cjolly3053/Desktop/RecentClips/2019-08-21_08-00-33-left_repeater.mp4', '-i', '/Users/cjolly3053/Desktop/RecentClips/2019-08-21_08-00-33-front.mp4', '-i', '/Users/cjolly3053/Desktop/RecentClips/2019-08-21_08-00-33-right_repeater.mp4', '-filter_complex', "color=duration=58.91:s=1280x960:c=black [base];[0:v] setpts=PTS-STARTPTS, scale=640x480 , hflip [left];[1:v] setpts=PTS-STARTPTS, scale=640x480  [front];[2:v] setpts=PTS-STARTPTS, scale=640x480 , hflip [right];[base][left] overlay=eof_action=pass:repeatlast=0:x=0:y=480 [left1];[left1][front] overlay=eof_action=pass:repeatlast=0:x=320:y=0 [front1];[front1][right] overlay=eof_action=pass:repeatlast=0:x=640:y=480[tmp0];[tmp0] drawtext=fontfile=/Library/Fonts/Arial.ttf:fontcolor=white:fontsize=16.0:borderw=2:bordercolor=black@1.0:x=(w/2-text_w/2):y=(h-(text_h*2)):text='%{pts\\:localtime\\:1566392434\\:%x %X}'", '-preset', 'medium', '-crf', '28', '-allow_sw', '1', '-b:v', '5000K', '-c:v', 'h264_videotoolbox', '-y', '/Users/cjolly3053/Movies/Tesla_Dashcam/2019-08-21_08-00-33.mp4']
			Error: b"ffmpeg version N-93225-g37e4c226c0-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers\n  built with Apple LLVM version 10.0.0 (clang-1000.11.45.5)\n  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay\n  libavutil      56. 26.100 / 56. 26.100\n  libavcodec     58. 47.102 / 58. 47.102\n  libavformat    58. 26.101 / 58. 26.101\n  libavdevice    58.  6.101 / 58.  6.101\n  libavfilter     7. 48.100 /  7. 48.100\n  libswscale      5.  4.100 /  5.  4.100\n  libswresample   3.  4.100 /  3.  4.100\n  libpostproc    55.  4.100 / 55.  4.100\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/cjolly3053/Desktop/RecentClips/2019-08-21_08-00-33-left_repeater.mp4':\n  Metadata:\n    major_brand     : mp42\n    minor_version   : 0\n    compatible_brands: mp42mp41isomiso2\n    creation_time   : 2019-08-21T13:00:34.000000Z\n  Duration: 00:00:58.91, start: 0.000000, bitrate: 4011 kb/s\n    Stream #0:0(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1280x960, 4006 kb/s, SAR 1:1 DAR 4:3, 35.98 fps, 36 tbr, 10k tbn, 20k tbc (default)\n    Metadata:\n      creation_time   : 2019-08-21T13:00:34.000000Z\n      handler_name    : VideoHandler\nInput #1, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/cjolly3053/Desktop/RecentClips/2019-08-21_08-00-33-front.mp4':\n  Metadata:\n    major_brand     : mp42\n    minor_version   : 0\n    compatible_brands: mp42mp41isomiso2\n    creation_time   : 2019-08-21T13:00:35.000000Z\n  Duration: 00:00:57.72, start: 0.000000, bitrate: 3185 kb/s\n    Stream #1:0(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1280x960, 3180 kb/s, SAR 1:1 DAR 4:3, 35 fps, 36 tbr, 10k tbn, 20k tbc (default)\n    Metadata:\n      creation_time   : 2019-08-21T13:00:35.000000Z\n      handler_name    : VideoHandler\nInput #2, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/cjolly3053/Desktop/RecentClips/2019-08-21_08-00-33-right_repeater.mp4':\n  Metadata:\n    major_brand     : mp42\n    minor_version   : 0\n    compatible_brands: mp42mp41isomiso2\n    creation_time   : 2019-08-21T13:00:35.000000Z\n  Duration: 00:00:58.38, start: 0.000000, bitrate: 3993 kb/s\n    Stream #2:0(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1280x960, 3987 kb/s, SAR 1:1 DAR 4:3, 35.99 fps, 36 tbr, 10k tbn, 20k tbc (default)\n    Metadata:\n      creation_time   : 2019-08-21T13:00:35.000000Z\n      handler_name    : VideoHandler\nFontconfig error: Cannot load default config file\n[Parsed_drawtext_12 @ 0x7f8de950bd40] Cannot find a valid font for the family Sans\n[AVFilterGraph @ 0x7f8de9502a40] Error initializing filter 'drawtext' with args 'fontfile=/Library/Fonts/Arial.ttf:fontcolor=white:fontsize=16.0:borderw=2:bordercolor=black@1.0:x=(w/2-text_w/2):y=(h-(text_h*2)):text=%{pts\\:localtime\\:1566392434\\:%x %X}'\nError initializing complex filters.\nNo such file or directory\n"

**Comment by ehendrix23** [comment]
Can you provide the full command you use?

Further, please check if file /Library/Fonts/Arial.ttf exist (it should).

**Comment by cjolly3053** [comment]
Was simply trying just the ./tesla_dashcam by itself at first. This has worked in the past.

It does find my drive and finds the files in it.

/Library/Fonts/ is only showing Arial Unicode.ttf ?

--------------------------------
Chris Jolly
cjolly3053@gmail.com

**Comment by ehendrix23** [comment]
Hmm, something happened with your Fonts folder then.

Here are all the Arial fonts I have:
/Library/Fonts/Arial Black.ttf
/Library/Fonts/Arial Bold Italic.ttf
/Library/Fonts/Arial Bold.ttf
/Library/Fonts/Arial Italic.ttf
/Library/Fonts/Arial Narrow Bold Italic.ttf
/Library/Fonts/Arial Narrow Bold.ttf
/Library/Fonts/Arial Narrow Italic.ttf
/Library/Fonts/Arial Narrow.ttf
/Library/Fonts/Arial Rounded Bold.ttf
/Library/Fonts/Arial Unicode.ttf
/Library/Fonts/Arial.ttf

And clearly a lot more other non-Arial font files as well.

**Comment by cjolly3053** [comment]
Hmmmm yeah even the /system/library/fonts folder does not show one. Let me see if I can solve that first then give more feedback

**Comment by cjolly3053** [comment]
So I did find them and copied them to the /library/fonts/ folder and it looks like that DID fix the issue.

It’s going trough the videos now so I am assuming it will complete.

They were in /system/library/fonts/Supplemental/

--------------------------------
Chris Jolly
cjolly3053@gmail.com

**Comment by ehendrix23** [comment]
Hmm, weird that this happened. Glad to hear it is resolved. 

Just added check for existence of font file (be it default or provided through option) making it more obvious then for cases like this. :-)

Will be closing this issue.
