### ISSUE TITLE
tesla_dashcam on Homebrew ?

### ISSUE THREAD

**Issue by haakonstorm** [ehendrix23/tesla_dashcam#63]
Please add a formulae (or cask) for tesla_dashcam to Homebrew:
- https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md
- https://docs.brew.sh/Formula-Cookbook

Really it should be installed as a `cask` but due to the guidelines (software is both open source *and* cli-only) it should be added as a brew formulae first, then rejected, then migrated to a `cask`:

> The app is both open-source and CLI-only (i.e. it only uses the binary artifact). In that case, and in the spirit of deduplication, submit it first to Homebrew/core as a formula that builds from source. If it is rejected, you may then try again as a cask (link us to the issue so we can see the discussion and reasoning for rejection).

- https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md

I could help in doing this, but I think it is better that the repo owner also has complete control on distribution. If you think otherwise please notify me and I'll look into starting the brew process.

Way easier to install this project via Homebrew, simply like so:

`brew install tesla_dashcam`

or

`brew cask install tesla_dashcam`

:)

**Comment by ehendrix23** [comment]
I'll look into this and get back to you. Never done this before so will need to check how it's done etc.. :-)

**Comment by haakonstorm** [comment]
Great! I've never done it myself - I was on the verge of just going ahead and doing it, but two things made me think twice:
- the issue with the app being both open-source and CLI-only
- the issue with upgrades; how to make sure that `brew upgrade tesla_dashcam` works wit future versions of your utility.

Looking forward to seeing how this is resolved! Adoption of your utility will greatly increase, I think, when users can simply:

`brew install tesla_dashcam`

On a side note, as a long time Homebrew user, the "standard" naming convention would probaby suggest a name change to `tesla-dashcam`, replacing the underscore `_` with the standard hyphen (`-`). This might very well be irrellevant or erronous on my part, I guess you'll see when submitting to brew. This is a partial output of my ´brew list` :

```
(...)
aom			icu4c			libtool			pixman
augeas			ilmbase			libunistring		pkg-config
bitchx			itermocil		libuv			python
coreutils		jq			libwebsockets		rtmpdump
curl			jump			little-cms2		rubberband
dialog			lame			lua			ruby-build
dnsmasq			leptonica		lzo			sdl2
exiftool		libass			mas			shared-mime-info
ffmpeg			libassuan		mdcat			snappy
figlet			libbluray		mint			sourcery
flac			libcaca			mosquitto		speex
fontconfig		libde265		multimarkdown		sqlite
freetype		libevent		nativefier		ssh-copy-id
fribidi			libgcrypt		nettle			swiftlint
gdbm			libgpg-error		nmap			tag
git			libksba			oniguruma		toilet
glib			libmaxminddb		opencore-amr		unbound
gnutls			libpng			openssl			x264
go			libsamplerate		openssl@1.1		x265
goku			libsndfile		opus			xvid
graphite2		libsoxr			p11-kit			xz
harfbuzz		libsvg			pandoc
haskell-stack		libsvg-cairo		pcre
```

Mostly straight `-`'s but that doesn't mean underscores `_` aren't permitted.
