### ISSUE TITLE
FR: Add Raspberry as an option for GPU

### ISSUE THREAD

**Issue by PiscisSwimeatus** [ehendrix23/tesla_dashcam#66]
Raspberry Pis can do hardware acceleration with h264_mmal decode and h264_omx encode.
Could we have this added as an option to GPU?

https://trac.ffmpeg.org/wiki/HWAccelIntro

**Comment by ehendrix23** [comment]
I'll look into it. Next version has option to specify GPU (currently NVIDIA and Intel), hence I can add it in there for option.
Would you be able to pull the code from GitHub and test once I have it in there?

**Comment by PiscisSwimeatus** [comment]
Great, just give me a notification when its ready and I'll test.

Been testing the nvidia one for now.
As far as I can see its only HW encoding, decoding looks to be SW and not HW?

**Comment by PiscisSwimeatus** [comment]
Also the new --gpu_type throws me an error:

python tesla_dashcam.py --mirror --gpu --gpu_type="nvidia" --scale="0.5" --quality="MEDIUM" --output="C:\Users\xyz\Temp\Tesla_Dashcam" --monitor_trigger "C:\Users\xyz\Downloads"

GPU acceleration is enabled
Traceback (most recent call last):
  File "tesla_dashcam.py", line 2657, in <module>
    sys.exit(main())
  File "tesla_dashcam.py", line 2368, in main
    video_encoding = video_encoding + ["-c:v", MOVIE_ENCODING[encoding]]
KeyError: 'x264nvidia'

**Comment by ehendrix23** [comment]
That error should be resolved now.
Further, added support for Raspberry Pi h.264 encoding. Looks like h.265 is not support for it.

For decoding, was just looking into this but docs for FFmpeg also state:
`Note that most acceleration methods are intended for playback and will not be faster than software decoding on modern CPUs.`

And when I added it I was having issues. So not sure based on what they state there if there would be a real benefit in it.

**Comment by PiscisSwimeatus** [comment]
Thanks, tested the HW encoding now on a Zero and it works (Getting 1 fps so not usable for converting, will test the 4b later today).

Tested SW vs HW decoding on an NVidia 980ti & Intel 6700K, and as docs says there is really no difference between the two. 

On the Pis however it might be different due to slower CPUs, but decoding is a pay to use function and not available for the 4b. I only have a Zero (Unusable for converting) and a 4b (No HW decoding) so not really in a position to test.

Thanks again, I'll close this issue now.

**Comment by ehendrix23** [comment]
Thank you.

Release 0.1.14 is out now including this enhancement
