### ISSUE TITLE
FR: Set folder for intermediate files

### ISSUE THREAD

**Issue by PiscisSwimeatus** [ehendrix23/tesla_dashcam#67]
Would it be possible to add the option to set folder for intermediate files? I currently have plex monitoring the output folder and all these intermediate files gets added (before they get deleted) as well as the finished output.

**Comment by ehendrix23** [comment]
Using, for example, a parameter like --temp_dir?

**Comment by PiscisSwimeatus** [comment]
Yes that would be great

**Comment by ehendrix23** [comment]
Release 0.1.13 will have it

**Comment by ehendrix23** [comment]
Thank you.

Release 0.1.14 is out now including this enhancement
