### ISSUE TITLE
Not prosessing all clips sometime after the 4th sep. commit.

### ISSUE THREAD

**Issue by PiscisSwimeatus** [ehendrix23/tesla_dashcam#68]
**The 4th sep. commit runs everything fine:**

C:\Users\aj\Downloads\tesla_dashcam>python tesla_dashcam_old.py --mirror --gpu --scale="1" --quality="MEDIUM" --output="C:\Users\aj\Temp" --monitor_trigger "\\10.47.0.205\TeslaCam"
GPU acceleration is enabled
Monitoring for trigger \\10.47.0.205\TeslaCam to exist. Press CTRL-C to stop
Trigger \\10.47.0.205\TeslaCam exist.
Retrieving all files from \\10.47.0.205\TeslaCam\SavedClips
Discovered 2 folders containing total of 33 files, retrieving clip data.
There are 1 folders with 11 clips to process.
        Processing 11 clips in folder \\10.47.0.205\TeslaCam\SavedClips\2019-09-10_07-30-27 (1/1)
                Processing clip 1/11 from 09/10/19 07:19:57 and 58 seconds long.
                Processing clip 2/11 from 09/10/19 07:20:57 and 58 seconds long.
                Processing clip 3/11 from 09/10/19 07:21:57 and 58 seconds long.
                Processing clip 4/11 from 09/10/19 07:22:58 and 57 seconds long.
                Processing clip 5/11 from 09/10/19 07:23:58 and 58 seconds long.
                Processing clip 6/11 from 09/10/19 07:24:58 and 58 seconds long.
                Processing clip 7/11 from 09/10/19 07:25:58 and 58 seconds long.
                Processing clip 8/11 from 09/10/19 07:26:59 and 58 seconds long.
                Processing clip 9/11 from 09/10/19 07:27:59 and 58 seconds long.
                Processing clip 10/11 from 09/10/19 07:29:00 and 57 seconds long.
                Processing clip 11/11 from 09/10/19 07:30:00 and 19 seconds long.
                Creating movie C:\Users\aj\Temp\2019-09-10T07-19-57_2019-09-10T07-30-19.mp4, please be patient.
        Movie C:\Users\aj\Temp\2019-09-10T07-19-57_2019-09-10T07-30-19.mp4 for folder \\10.47.0.205\TeslaCam\SavedClips\2019-09-10_07-30-27 with duration 0:10:00 is ready.
All folders have been processed, resulting movie files are located in C:\Users\aj\Temp
Total processing time: 0:05:23

Processing of movies has completed.
Exiting monitoring as asked process once.

**However the most recent commit is broken:**

C:\Users\aj\Downloads\tesla_dashcam>python tesla_dashcam.py --mirror --gpu --gpu_type="nvidia" --scale="1" --quality="MEDIUM" --output="C:\Users\aj\Temp" --monitor_trigger "\\10.47.0.205\TeslaCam"
GPU acceleration is enabled
Monitoring for trigger \\10.47.0.205\TeslaCam to exist. Press CTRL-C to stop
Trigger \\10.47.0.205\TeslaCam exist.
Retrieving all files from \\10.47.0.205\TeslaCam\SavedClips
Discovered 2 folders containing total of 33 files, retrieving clip data.
There are 1 folders with 11 clips to process.
        Processing 11 clips in folder \\10.47.0.205\TeslaCam\SavedClips\2019-09-10_07-30-27 (1/1)
                **Processing clip 1/11 from 09/10/19 07:19:57 and 58 seconds long.
                Processing clip 11/11 from 09/10/19 07:30:00 and 19 seconds long.**
                Creating movie C:\Users\aj\Temp\2019-09-10T07-19-57_2019-09-10T07-30-19.mp4, please be patient.
        Movie C:\Users\aj\Temp\2019-09-10T07-19-57_2019-09-10T07-30-19.mp4 for folder \\10.47.0.205\TeslaCam\SavedClips\2019-09-10_07-30-27 with duration 0:01:17 is ready.
All folders have been processed, resulting movie files are located in C:\Users\aj\Temp
Total processing time: 0:00:36

Processing of movies has completed.
Exiting monitoring as asked process once.

**Comment by supRy** [comment]
I have also observed this issue

**Comment by ehendrix23** [comment]
Check last commit from today (Sept 19). Should fix this issue.

**Comment by PiscisSwimeatus** [comment]
Confirmed working thank you

C:\Users\aj\Temp>python tesla_dashcam.py --mirror --gpu --gpu_type nvidia --scale="1" --quality="MEDIUM" --output="C:\Users\aj\Temp" --monitor_trigger H:\TeslaCam
GPU acceleration is enabled
Monitoring for trigger H:\TeslaCam to exist. Press CTRL-C to stop
Trigger H:\TeslaCam exist.
Retrieving all files from H:\TeslaCam\SavedClips
Discovered 12 folders containing total of 270 files, retrieving clip data.
There are 11 folders with 90 clips to process.
        Processing 11 clips in folder H:\TeslaCam\SavedClips\2019-09-18_07-32-16 (1/11)
                Processing clip 1/11 from 09/18/19 07:21:58 and 59 seconds long.
                Processing clip 2/11 from 09/18/19 07:22:59 and 57 seconds long.
                Processing clip 3/11 from 09/18/19 07:23:59 and 58 seconds long.
                Processing clip 4/11 from 09/18/19 07:25:00 and 58 seconds long.
                Processing clip 5/11 from 09/18/19 07:26:00 and 57 seconds long.
                Processing clip 6/11 from 09/18/19 07:27:00 and 58 seconds long.
                Processing clip 7/11 from 09/18/19 07:28:00 and 58 seconds long.
                Processing clip 8/11 from 09/18/19 07:29:01 and 58 seconds long.
                Processing clip 9/11 from 09/18/19 07:30:01 and 58 seconds long.
                Processing clip 10/11 from 09/18/19 07:31:01 and 58 seconds long.
                Processing clip 11/11 from 09/18/19 07:32:02 and 3 seconds long.
                Creating movie C:\Users\aj\Temp\2019-09-18T07-21-58_2019-09-18T07-32-05.mp4, please be patient.
        Movie C:\Users\aj\Temp\2019-09-18T07-21-58_2019-09-18T07-32-05.mp4 for folder H:\TeslaCam\SavedClips\2019-09-18_07-32-16 with duration 0:09:46 is ready.
