### ISSUE TITLE
Support v10 rear_view vids

### ISSUE THREAD

**Issue by emorog** [ehendrix23/tesla_dashcam#71]
New to v10, clips now contain the rear camera, named \<timestamp>-rear_view.mp4
Need an option to include this vid in the output.

**Comment by ehendrix23** [comment]
Currently being worked upon for next version.

**Comment by emorog** [comment]
F:\TeslaCam\SentryClips\2019-09-25_15-52-29

**Comment by ehendrix23** [comment]
Thank you.

Release 0.1.14 is out now including support
