### ISSUE TITLE
No module named dateutil (pip 0.1.14, Server 2019)

### ISSUE THREAD

**Issue by raushel** [ehendrix23/tesla_dashcam#77]
pip install 0.1.14, server 2019, unable to run tesla_dashcam without this error:

![image](https://user-images.githubusercontent.com/49056263/65845533-3e863a00-e300-11e9-8cdf-c53d4e8c35de.png)

**Comment by raushel** [comment]
Had to install python-dateutil to resolve:

pip install python-dateutil

**Comment by ehendrix23** [comment]
Thank you. Missed adding that package to setup file. 

Just released 0.1.15 with fix.
