### ISSUE TITLE
v10 back camera filenames changed

### ISSUE THREAD

**Issue by flops242** [ehendrix23/tesla_dashcam#78]
Thank you for your awesome tool and the support of the new back camera files in v10!

Not sure if this is a european thing only or Tesla changed it for everyone in the firmware version 2019.32.11 (bac8c51) but the files on my thumb drive were all called "-back.mp4" instead of what your script currently expects ("-rear_view.mp4").
Maybe others can confirm the filenames really changed for good and the script should be adapted, else a command line switch or looking for both types of filenames might be helpful. Thanks!

**Comment by jaimevisser** [comment]
Same here. EU M3. Rear files are named -back.mp4.

**Comment by ehendrix23** [comment]
Going to check with mine a bit later, but I think it was a "last" change from Tesla or so in naming it. Fix forthcoming. :-)

**Comment by ehendrix23** [comment]
US version is -back as well.

**Comment by sumnerboy12** [comment]
NZ version is `-back` also...

**Comment by ehendrix23** [comment]
Just released 0.1.15 with fix.
