### ISSUE TITLE
After much time processing the input got an ugly stacktrace with "Invalid Argument" - should fail fast instead

### ISSUE THREAD

**Issue by anibal2j** [ehendrix23/tesla_dashcam#8]
I have a folder with 33 mp4 files. I issued this command:

tesla_dashcam --source . --output new

Thinking that new would be a new folder created with the output. After processing all the files I got the following:

Anibals-MacBook-Air-2:2019-04-03_11-46-47 anibal$ tesla_dashcam --source . --output new
Processing clip 1/11 from 04/03/19 11:36:13 and 60 seconds long.
Processing clip 2/11 from 04/03/19 11:37:14 and 60 seconds long.
Processing clip 3/11 from 04/03/19 11:38:15 and 60 seconds long.
Processing clip 4/11 from 04/03/19 11:39:17 and 59 seconds long.
Processing clip 5/11 from 04/03/19 11:40:18 and 60 seconds long.
Processing clip 6/11 from 04/03/19 11:41:19 and 59 seconds long.
Processing clip 7/11 from 04/03/19 11:42:20 and 58 seconds long.
Processing clip 8/11 from 04/03/19 11:43:21 and 60 seconds long.
Processing clip 9/11 from 04/03/19 11:44:22 and 59 seconds long.
Processing clip 10/11 from 04/03/19 11:45:23 and 59 seconds long.
Processing clip 11/11 from 04/03/19 11:46:23 and 23 seconds long.
Creating movie new, please be patient.
Error trying to create movie new. RC: 1
Command: ['ffmpeg', '-i', './2019-04-03_11-36.mp4', '-i', './2019-04-03_11-37.mp4', '-i', './2019-04-03_11-38.mp4', '-i', './2019-04-03_11-39.mp4', '-i', './2019-04-03_11-40.mp4', '-i', './2019-04-03_11-41.mp4', '-i', './2019-04-03_11-42.mp4', '-i', './2019-04-03_11-43.mp4', '-i', './2019-04-03_11-44.mp4', '-i', './2019-04-03_11-45.mp4', '-i', './2019-04-03_11-46.mp4', '-filter_complex', '[0:v:0] [1:v:0] [2:v:0] [3:v:0] [4:v:0] [5:v:0] [6:v:0] [7:v:0] [8:v:0] [9:v:0] [10:v:0] concat=n=11:v=1:a=0 [v]', '-map', '[v]', '-c:v', 'libx264', '-preset', 'medium', '-crf', '28', '-y', 'new']
Error: b"ffmpeg version 4.1.1-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers\n  built with Apple LLVM version 10.0.0 (clang-1000.11.45.5)\n  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay\n  libavutil      56. 22.100 / 56. 22.100\n  libavcodec     58. 35.100 / 58. 35.100\n  libavformat    58. 20.100 / 58. 20.100\n  libavdevice    58.  5.100 / 58.  5.100\n  libavfilter     7. 40.101 /  7. 40.101\n  libswscale      5.  3.100 /  5.  3.100\n  libswresample   3.  3.100 /  3.  3.100\n  libpostproc    55.  3.100 / 55.  3.100\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from './2019-04-03_11-36.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.20.100\n  Duration: 00:01:00.04, start: 0.000000, bitrate: 532 kb/s\n    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x480 [SAR 1:1 DAR 4:1], 529 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\nInput #1, mov,mp4,m4a,3gp,3g2,mj2, from './2019-04-03_11-37.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.20.100\n  Duration: 00:01:00.32, start: 0.000000, bitrate: 788 kb/s\n    Stream #1:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x480 [SAR 1:1 DAR 4:1], 786 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\nInput #2, mov,mp4,m4a,3gp,3g2,mj2, from './2019-04-03_11-38.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.20.100\n  Duration: 00:01:00.28, start: 0.000000, bitrate: 538 kb/s\n    Stream #2:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x480 [SAR 1:1 DAR 4:1], 535 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\nInput #3, mov,mp4,m4a,3gp,3g2,mj2, from './2019-04-03_11-39.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.20.100\n  Duration: 00:01:00.00, start: 0.000000, bitrate: 655 kb/s\n    Stream #3:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x480 [SAR 1:1 DAR 4:1], 652 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\nInput #4, mov,mp4,m4a,3gp,3g2,mj2, from './2019-04-03_11-40.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.20.100\n  Duration: 00:01:00.32, start: 0.000000, bitrate: 530 kb/s\n    Stream #4:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x480 [SAR 1:1 DAR 4:1], 527 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\nInput #5, mov,mp4,m4a,3gp,3g2,mj2, from './2019-04-03_11-41.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.20.100\n  Duration: 00:00:59.28, start: 0.000000, bitrate: 496 kb/s\n    Stream #5:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x480 [SAR 1:1 DAR 4:1], 493 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\nInput #6, mov,mp4,m4a,3gp,3g2,mj2, from './2019-04-03_11-42.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.20.100\n  Duration: 00:00:58.96, start: 0.000000, bitrate: 572 kb/s\n    Stream #6:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x480 [SAR 1:1 DAR 4:1], 569 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\nInput #7, mov,mp4,m4a,3gp,3g2,mj2, from './2019-04-03_11-43.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.20.100\n  Duration: 00:01:00.48, start: 0.000000, bitrate: 1049 kb/s\n    Stream #7:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x480 [SAR 1:1 DAR 4:1], 1047 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\nInput #8, mov,mp4,m4a,3gp,3g2,mj2, from './2019-04-03_11-44.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.20.100\n  Duration: 00:00:59.28, start: 0.000000, bitrate: 407 kb/s\n    Stream #8:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x480 [SAR 1:1 DAR 4:1], 404 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\nInput #9, mov,mp4,m4a,3gp,3g2,mj2, from './2019-04-03_11-45.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.20.100\n  Duration: 00:00:59.52, start: 0.000000, bitrate: 388 kb/s\n    Stream #9:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x480 [SAR 1:1 DAR 4:1], 386 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\nInput #10, mov,mp4,m4a,3gp,3g2,mj2, from './2019-04-03_11-46.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    encoder         : Lavf58.20.100\n  Duration: 00:00:23.00, start: 0.000000, bitrate: 285 kb/s\n    Stream #10:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x480 [SAR 1:1 DAR 4:1], 282 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\n[NULL @ 0x7fd06605b000] Unable to find a suitable output format for 'new'\nnew: Invalid argument\n"

I suggest doing some more processing in the input parameters to see if it's going to work or not. I had to wait about 10 minutes before it failed. I'm still not clear what's wrong, since I can see the new mp4 files created.

**Comment by ehendrix23** [comment]
Definitely do not have the latest version. Grab the latest version from here:
https://github.com/ehendrix23/tesla_dashcam/releases/download/v0.1.8/tesla_dashcam.dmg

In the mean time I'll see to simulate what you provided for command. :-)

**Comment by ehendrix23** [comment]
FYI, I just tested similar to what you provided with the new version:
`tesla_dashcam --output new .`
executing from within the folder that contains the video files and it worked. So please get the latest version and try again.
Let me know if it worked or not. :-)

**Comment by anibal2j** [comment]
Yes, worked well. Looks good now.

**Comment by ehendrix23** [comment]
Excellent, will be closing this issue then. :-)
