### ISSUE TITLE
framerate improvement

### ISSUE THREAD

**Issue by JamesKrieger** [ehendrix23/tesla_dashcam#85]
Tesla video source are at generate between 35 to 36 fps.
during the conversation, the video is down sample to 25 fps. 
Propose to keep same rate as the source. (or take the higher frame rate.)

**Comment by JamesKrieger** [comment]
instead of the default 25fps, the new framerate can be specify on the first stream.
below the example to set the framerate to 60

'-filter_complex', "color=duration=58.48:s=3840x1920:c=black ,fps=60  [base];

**Comment by ehendrix23** [comment]
Added in release 0.1.16
