### ISSUE TITLE
Missing Key frame

### ISSUE THREAD

**Issue by c-E-c-777** [ehendrix23/tesla_dashcam#87]
I managed to get this project running on a Debian box and most videos are merged without issue, however, I am receiving an error occasionally which seems to end up creating a zero length file in the 'MergedClips' (output dir) folder, at which point it seems to skip to the next file in the group. The particular group of clips are still pieced together into a single merged video file when completed, but it does appear that the particular section of video which threw the error is not included; i.e., clip 2/10 fails and therefore the second minute of footage is skipped in the final output. I believe this may just be something with ffmpeg and perhaps Linux, but hopefully someone smarter than me can shed some light on it. Below is a sample of the error message received.

Missing key frame while reordering index according to edit list\n[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55dbe10f64e0] Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 1280x960, 5225 kb/s): unspecified pixel format\nConsider increasing the value for the \'analyzeduration\' and \'probesize\' options\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from \'/media/disk01/Tesla/SavedClips/2019-10-01_07-52-33/2019-10-01_07-49-29-left_repeater.mp4\

**Comment by ehendrix23** [comment]
What is the size of file 2019-10-01_07-49-29-left_repeater.mp4?
