### ISSUE TITLE
Not an issue, just a request

### ISSUE THREAD

**Issue by peabitty** [ehendrix23/tesla_dashcam#88]
Hi. I love the app and I can't find any other way to contact you. I would like to support what you're doing. Do you have a Patreon or PayPal I could send some money to say thanks?

**Comment by bcarrick** [comment]
100% agree. I got money for you also. This ability to consume hours of video in minutes is a high value return.

Please provide a way to contribute financially.

**Comment by ehendrix23** [comment]
Thank you both. No need to contribute. Doing this as a hobby in my spare time. I see it as a way to give to the community similar as so many others do. :-)
I use free software, free advice, seek help from the community. This is my way to pay back.
