### ISSUE TITLE
RecentClips not processed

### ISSUE THREAD

**Issue by jerrycallahan66** [ehendrix23/tesla_dashcam#91]
If I set the source to TeslaCam, tesla_dashcam program finds the SavedClips and SentryClips but ignores RecentClips. They are not in subfolders but the program should process them. These are the files I am most interested in seeing.

Followup:
I did several more tests on the command line entries.
1. I could not duplicate the original problem in part because I did not save the exact data.
2. In the past I never got the @ splat to work for my_perference.txt but your program found it by default. The current version did not find my options file. I did extensive testing on the command line and found that I could get windows powershell to take the splat if I put it in quotes.
3. The tesla_dashcam program seems to be hard coded to look only on the E: drive by default. My Dell PC wants to assign my front USB ports to the F: drive. So I have to explicitly declare that drive as source. The program will in-fact now find all three TeslaCam subdirectories as in my original statement. Better yet, it processes the the RecentClips files.

Here is my working command line:
> cd C:\users\jerry\bin\tesla_dashcam
> C:\Users\Jerry\bin\tesla_dashcam\tesla_dashcam\tesla_dashcam.exe "@my_preference.txt" F:

Here is my_preference.txt content:
--speedup 10 
--merge 
--layout FULLSCREEN
--mirror
--fontcolor white
--fontsize 24
--valign TOP
--halign LEFT
--quality MEDIUM
--encoding x265
--output C:\Users\Jerry\Videos\MyTeslaCam\

**Comment by ehendrix23** [comment]
Can you provide me the complete command you provide?

**Comment by ehendrix23** [comment]
Any chance you have a folder TeslaCam on your E-drive (E:\TeslaCam)?

When running without providing a full source path (or no source at all) the script will then check for any disks (partitions) that have a folder named TeslaCam on the root. If not it will wait until there is a disk (USB) inserted with a folder named TeslaCam in it's root.
Thus if you have a E:\TeslaCam then it would find that and use it. 

When not providing a source only SavedClips and SentryClips are being processed automatically. RecentClips will not. As you provide F: now, it will scan all sub-folder of the source provided (F) and hence include RecentClips.

If you do not want to provide a drive letter (and thus have it scan for a drive with TeslaCam folder on it) but still want to process all 3 folders then you can just provide as source `RecentClips SavedClips SentryClips`.

Hope this helps.

**Comment by jerrycallahan66** [comment]
I do not have any TeslaCam folders on my drives, except when I plug in my USB drive.

 

I do not seem to have control over when Windows will assign the USB drive to E: or F: drive when I use my Dell front panel ports.

 

Thanks for explaining a work-around to pick up all three folders.

 

Cheers,

Jerry Callahan
