### ISSUE TITLE
No clips found on macOS 10.15 Catalina

### ISSUE THREAD

**Issue by khorton** [ehendrix23/tesla_dashcam#92]
I'm running v0.1.16b0, but had the same issue on v0.1.15.  On both Macs running 10.15 Catalina, I get a "No clips found".  Full output is:

'python3 /Users/kwh/bin/tesla_dashcam.py --rear  --motion_only --font /Library/Fonts/Arial\ Unicode.ttf --output ~/Movies/Tesla_Dashcam .
GPU acceleration is enabled
Discovered 11 folders containing total of 409 files in .
There are 10 folders with 103 clips to process.
	Processing 11 clips in folder ./2019-10-07_18-47-55 (1/10)
	Processing 6 clips in folder ./2019-10-07_18-54-05 (2/10)
	Processing 11 clips in folder ./2019-10-09_06-54-35 (3/10)
	Processing 11 clips in folder ./2019-10-09_07-22-33 (4/10)
	Processing 11 clips in folder ./2019-10-10_17-18-26 (5/10)
	Processing 11 clips in folder ./2019-10-12_10-30-37 (6/10)
	Processing 10 clips in folder ./2019-10-14_07-35-47 (7/10)
	Processing 11 clips in folder ./2019-10-14_08-01-03 (8/10)
	Processing 10 clips in folder ./2019-10-14_08-24-29 (9/10)
	Processing 11 clips in folder ./2019-10-14_09-30-52 (10/10)
No clips found.
Total processing time: 0:00:00
'

No merged video files are created in ~/Movies/Tesla_Dashcam.

v0.1.12 was working perfectly for me on macOS 10.14, but I upgraded to the later script as my Tesla now has v10, and I wanted to also merge the rear camera video files.

What additional info can I provide, or tests can I run, to help debug this?

Thanks for a great script (when it works :)

**Comment by khorton** [comment]
ls -al for first folder:

'-rwxr-xr-x   1 kwh  staff    36M Oct 15 07:26 2019-10-07_18-37-23-back.mp4
-rwxr-xr-x   1 kwh  staff    35M Oct 15 07:26 2019-10-07_18-37-23-front.mp4
-rwxr-xr-x   1 kwh  staff    34M Oct 15 07:26 2019-10-07_18-37-23-left_repeater.mp4
-rwxr-xr-x   1 kwh  staff    34M Oct 15 07:26 2019-10-07_18-37-23-right_repeater.mp4
-rwxr-xr-x   1 kwh  staff    36M Oct 15 07:26 2019-10-07_18-38-24-back.mp4
-rwxr-xr-x   1 kwh  staff    34M Oct 15 07:26 2019-10-07_18-38-24-front.mp4
-rwxr-xr-x   1 kwh  staff    35M Oct 15 07:26 2019-10-07_18-38-24-left_repeater.mp4
-rwxr-xr-x   1 kwh  staff    34M Oct 15 07:26 2019-10-07_18-38-24-right_repeater.mp4
-rwxr-xr-x   1 kwh  staff    35M Oct 15 07:26 2019-10-07_18-39-25-back.mp4
-rwxr-xr-x   1 kwh  staff    35M Oct 15 07:26 2019-10-07_18-39-25-front.mp4
-rwxr-xr-x   1 kwh  staff    35M Oct 15 07:26 2019-10-07_18-39-25-left_repeater.mp4
-rwxr-xr-x   1 kwh  staff    34M Oct 15 07:26 2019-10-07_18-39-25-right_repeater.mp4
-rwxr-xr-x   1 kwh  staff    36M Oct 15 07:26 2019-10-07_18-40-26-back.mp4
-rwxr-xr-x   1 kwh  staff    35M Oct 15 07:26 2019-10-07_18-40-26-front.mp4
-rwxr-xr-x   1 kwh  staff    35M Oct 15 07:26 2019-10-07_18-40-26-left_repeater.mp4
-rwxr-xr-x   1 kwh  staff    35M Oct 15 07:26 2019-10-07_18-40-26-right_repeater.mp4
-rwxr-xr-x   1 kwh  staff    37M Oct 15 07:26 2019-10-07_18-41-26-back.mp4
-rwxr-xr-x   1 kwh  staff    36M Oct 15 07:26 2019-10-07_18-41-26-front.mp4
-rwxr-xr-x   1 kwh  staff    35M Oct 15 07:26 2019-10-07_18-41-26-left_repeater.mp4
-rwxr-xr-x   1 kwh  staff    36M Oct 15 07:26 2019-10-07_18-41-26-right_repeater.mp4
-rwxr-xr-x   1 kwh  staff    37M Oct 15 07:26 2019-10-07_18-42-27-back.mp4
-rwxr-xr-x   1 kwh  staff    35M Oct 15 07:26 2019-10-07_18-42-27-front.mp4
-rwxr-xr-x   1 kwh  staff    35M Oct 15 07:26 2019-10-07_18-42-27-left_repeater.mp4
-rwxr-xr-x   1 kwh  staff    35M Oct 15 07:26 2019-10-07_18-42-27-right_repeater.mp4
-rwxr-xr-x   1 kwh  staff    36M Oct 15 07:26 2019-10-07_18-43-27-back.mp4
-rwxr-xr-x   1 kwh  staff    36M Oct 15 07:26 2019-10-07_18-43-27-front.mp4
-rwxr-xr-x   1 kwh  staff    35M Oct 15 07:26 2019-10-07_18-43-27-left_repeater.mp4
-rwxr-xr-x   1 kwh  staff    35M Oct 15 07:26 2019-10-07_18-43-27-right_repeater.mp4
-rwxr-xr-x   1 kwh  staff    36M Oct 15 07:26 2019-10-07_18-44-28-back.mp4
-rwxr-xr-x   1 kwh  staff    36M Oct 15 07:26 2019-10-07_18-44-28-front.mp4
-rwxr-xr-x   1 kwh  staff    36M Oct 15 07:26 2019-10-07_18-44-28-left_repeater.mp4
-rwxr-xr-x   1 kwh  staff    35M Oct 15 07:26 2019-10-07_18-44-28-right_repeater.mp4
-rwxr-xr-x   1 kwh  staff    36M Oct 15 07:26 2019-10-07_18-45-28-back.mp4
-rwxr-xr-x   1 kwh  staff    36M Oct 15 07:26 2019-10-07_18-45-28-front.mp4
-rwxr-xr-x   1 kwh  staff    35M Oct 15 07:26 2019-10-07_18-45-28-left_repeater.mp4
-rwxr-xr-x   1 kwh  staff    36M Oct 15 07:26 2019-10-07_18-45-28-right_repeater.mp4
-rwxr-xr-x   1 kwh  staff    36M Oct 15 07:26 2019-10-07_18-46-29-back.mp4
-rwxr-xr-x   1 kwh  staff    35M Oct 15 07:26 2019-10-07_18-46-29-front.mp4
-rwxr-xr-x   1 kwh  staff    35M Oct 15 07:26 2019-10-07_18-46-29-left_repeater.mp4
-rwxr-xr-x   1 kwh  staff    35M Oct 15 07:26 2019-10-07_18-46-29-right_repeater.mp4
-rwxr-xr-x   1 kwh  staff    12M Oct 15 07:26 2019-10-07_18-47-29-back.mp4
-rwxr-xr-x   1 kwh  staff    12M Oct 15 07:26 2019-10-07_18-47-29-front.mp4
-rwxr-xr-x   1 kwh  staff    12M Oct 15 07:26 2019-10-07_18-47-29-left_repeater.mp4
-rwxr-xr-x   1 kwh  staff    12M Oct 15 07:26 2019-10-07_18-47-29-right_repeater.mp4'

**Comment by ehendrix23** [comment]
Nothing seems to be abnormal there.

I just pushed out an updated version to the dev branch (0.1.16b1). Can you run that one with the option --loglevel DEBUG
That hopefully will let me know then why the files are being skipped. :-)

**Comment by khorton** [comment]
I'm not sure this is producing the output you hoped for.

'
python3 /Users/kwh/bin/tesla_dashcam.py --rear  --motion_only --font /Library/Fonts/Arial\ Unicode.ttf --loglevel DEBUG --output ~/Movies/Tesla_Dashcam .
2019-10-17 19:13:24,898:DEBUG:	__main__	Arguments : Namespace(background='black', chapter_offset=0, check_for_updates=False, clip_scale=None, compression='medium', delete_source=False, enc=None, encoding='x264', end_offset=None, end_timestamp=None, exclude_subdirs=False, faststart=False, ffmpeg='ffmpeg', font='/Library/Fonts/Arial Unicode.ttf', fontcolor='white', fontsize=None, fps=24, gpu=False, halign=None, include_beta=False, keep_intermediate=False, layout='FULLSCREEN', loglevel='DEBUG', merge_subdirs=False, monitor=False, monitor_once=False, monitor_trigger=None, motion_only=True, no_check_for_updates=False, no_front=False, no_left=False, no_rear=False, no_right=False, no_timestamp=False, output='/Users/kwh/Movies/Tesla_Dashcam', perspective=False, quality='LOWER', rear_or_mirror=0, skip_existing=False, slow_down=None, source=['SentryClips'], speed_up=None, start_offset=None, start_timestamp=None, swap_frontrear=False, swap_leftright=None, system_notification=True, temp_dir=None, valign=None)
Option --speed_up and option --slow_down cannot be used together, only use one of them.'

**Comment by ehendrix23** [comment]
Nope, not really. :-)

Just pushed fixes to dev branch for this.

**Comment by khorton** [comment]
Working now.  Thanks

**Comment by ehendrix23** [comment]
Closing
