### ISSUE TITLE
Docker information

### ISSUE THREAD

**Issue by magicalyak** [ehendrix23/tesla_dashcam#96]
There doesn't appear to much information on using docker here and it seems a bit underdeveloped.  Can one of the people who are using Docker perhaps add a readme for it?

From what I gather you can make this work by overriding the entrypoint with bash or mapping to /root/Videos/Tesla_Dashcam

How are people using this after that?  Are you running a disposable container that exits after processing?  WHat variables are you inputting?

**Comment by magicalyak** [comment]
Perhaps I'm overthinking this but could we add some stuff to the wiki maybe?
Looks like you can pass variables in such as
docker run tesla_dashcam -h

**Comment by magicalyak** [comment]
I've attempted to show a README and improved version here - I'm happy to just add this as a subdirectory (the README and Dockerfile should be very minimal and shouldn't affect current operations) or I can keep on my own.
https://github.com/magicalyak/tesla_dashcam
https://hub.docker.com/r/magicalyak/tesla_dashcam

**Comment by magicalyak** [comment]
i need to test this further (just a note to self)

**Comment by magicalyak** [comment]
This should be good to test, I welcome feedback on it.  I included example configurations in the README.rst

**Comment by ehendrix23** [comment]
I'll have a look at it. :-) I do not use Docker so fully dependent on others for this. :-)

**Comment by moorecp** [comment]
Looks like you've got something going, but this is how I'm using it currently:
`mv /path/to/local/TeslaCam/SavedClips/* /path/to/local/TeslaCam/ ; rm -R /path/to/local/TeslaCam/SavedClips ; mv /path/to/local/TeslaCam/SentryClips/* /path/to/local/TeslaCam/ ; rm -R /path/to/local/TeslaCam/SentryClips ; find /path/to/local/TeslaCam/ -mindepth 1 -type d -exec sh -c 'sudo docker run -it --rm -e TZ=America/Indiana/Indianapolis --network=host -v /path/to/local/TeslaCam:/TeslaCam tesla_dashcam --output /TeslaCam/$(basename $1).mp4 --rear --compression ultrafast --no-notification /TeslaCam/$(basename $2)' _ {} {} \; -exec mv {}.mp4 /path/to/local/TeslaCam\ Archive/Combined/ \; -exec mv {} /path/to/local/TeslaCam\ Archive/Raw/ \;`

**Comment by magicalyak** [comment]
@ehendrix23 wanted to ask if you'd be willing to create a Dockerhub repo based on this github to have a docker image available?  It should just build off the Dockerfile in the root and default to master (but you can point to any branch as default).

I am hosting my version [here](https://hub.docker.com/r/magicalyak/tesla_dashcam) (I am going to open a PR soon to update/replace the Dockerfile on yours) but the format is the same.  You just create the repo on dockerhub and point it here, it would then be  https://hub.docker.com/r/ehendrix23/tesla_dashcam and you could use it inline, for example: 
`docker run --rm -e TZ=America/New_York ehendrix23/tesla_dashcam -h`

**Comment by magicalyak** [comment]
@3rdStng can you open a new issue on this though?  That would be the right way to do new work instead of reopening a closed issue.

**Comment by 3rdStng** [comment]
Thank you @magicalyak. I was trying to get around to opening a new issue for you, but by the time I got around to it I saw you had already updated your docker image. I pulled the new update and my docker starts up just fine. (It didn't when I was manually trying to update it.) I need to get some sentry clips generated by the car to test if the issue is resolved. But thank you for the updates.
