### ISSUE TITLE
Windows Network Drive - 0 Files Found

### ISSUE THREAD

**Issue by SgtSeamonkey** [ehendrix23/tesla_dashcam#97]
Hey ehendrix23,

I used to pull all of my video clips from my USB Drive to a temp folder on my desktop - from there I would run tesla_dashcam from CMD and save the output files to my \users\Videos folder using the following commands:

cd C:\Users\xxx\Desktop\TeslaCam\tesla_dashcam v0.1.15
tesla_dashcam.exe --layout DIAMOND --quality HIGH --compression veryslow C:\Users\xxx\Desktop\TeslaCam\Vids

I hadn't done this in a while and had a large number of files to pull so to save SSD space I decided to move everything to my network share (on a server sitting next to my PC). Unfortunately, even following the exact same procedure I cannot find any files:

Microsoft Windows [Version 10.0.18362.418]
C:\Users\xxx>net use Z: \\xxx.xxx.xxx.xxx\Files
The command completed successfully.
C:\Users\xxx>Z:
Z:\>cd Z:\tesla_dashcam v0.1.15
Z:\tesla_dashcam v0.1.15>tesla_dashcam.exe --layout DIAMOND --quality HIGH --compression veryslow Z:\TeslaCam Vids Temp
There are 0 folders with 0 clips to process.
No clips found.
Total processing time: 0:00:00

However when I CD to that folder and use the dir command:

Z:\tesla_dashcam v0.1.15>cd Z:\TeslaCam Vids Temp
Z:\TeslaCam Vids Temp>dir
 Volume in drive Z is Files
 Volume Serial Number is xxxx-xxxx
 Directory of Z:\TeslaCam Vids Temp
10/23/2019  12:08 AM    <DIR>          .
10/23/2019  12:25 AM    <DIR>          ..
10/22/2019  11:40 PM    <DIR>          2019-10-08_23-00-03
10/22/2019  11:40 PM    <DIR>          2019-10-09_09-32-53
...
10/22/2019  07:23 PM        29,757,654 2019-10-22_22-22-25-left_repeater.mp4
10/22/2019  07:23 PM        29,717,598 2019-10-22_22-22-25-right_repeater.mp4
             200 File(s)  5,939,979,685 bytes
              93 Dir(s)  290,611,531,776 bytes free

--- Also wanted to say I really appreciate what you've made here. It's saved me a ton of headache sorting through video files!

**Comment by ehendrix23** [comment]
Looks like you have spaces in your path. Use the following then:
`tesla_dashcam.exe --layout DIAMOND --quality HIGH --compression veryslow "Z:\TeslaCam Vids Temp"`

**Comment by SgtSeamonkey** [comment]
Oh...well what a simple mistake I made. Sorry about that!

Thank you for the help!
