### ISSUE TITLE
0 folders and 0 files found

### ISSUE THREAD

**Issue by PcCrazii** [ehendrix23/tesla_dashcam#99]
(using windows powershell and .exe)
i made a preferences.txt and use the command tesla_dashcam preferences.txt
it returns this:

There are 0 folders with 0 clips to process.
No clips found.
Total processing time: 0:00:00

this is my preferences script
D:\TeslaCam\SentryClips --speedup 3  --monitor --layout CROSS --motion_only True --fontcolor yellowgreen@0.9 -halign CENTER -valign MIDDLE --quality MEDIUM

**Comment by ehendrix23** [comment]
Use:  `tesla_dashcam "@preferences.txt"` instead.
